// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_service/v26/account_service.proto
// Protobuf Java Version: 4.26.1

package api.gravity.v26;

public final class AccountServiceOuterClass {
  private AccountServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AddAccountRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.AddAccountRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string email = 1;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 1;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code api.gravity.v26.AddAccountRequest}
   */
  public  static final class AddAccountRequest extends
      com.google.protobuf.GeneratedMessageLite<
          AddAccountRequest, AddAccountRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.AddAccountRequest)
      AddAccountRequestOrBuilder {
    private AddAccountRequest() {
      email_ = "";
      password_ = "";
    }
    public static final int EMAIL_FIELD_NUMBER = 1;
    private java.lang.String email_;
    /**
     * <code>string email = 1;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      return email_;
    }
    /**
     * <code>string email = 1;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>string email = 1;</code>
     * @param value The email to set.
     */
    private void setEmail(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      email_ = value;
    }
    /**
     * <code>string email = 1;</code>
     */
    private void clearEmail() {

      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>string email = 1;</code>
     * @param value The bytes for email to set.
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      email_ = value.toStringUtf8();

    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.String password_;
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      return password_;
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(password_);
    }
    /**
     * <code>string password = 2;</code>
     * @param value The password to set.
     */
    private void setPassword(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      password_ = value;
    }
    /**
     * <code>string password = 2;</code>
     */
    private void clearPassword() {

      password_ = getDefaultInstance().getPassword();
    }
    /**
     * <code>string password = 2;</code>
     * @param value The bytes for password to set.
     */
    private void setPasswordBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      password_ = value.toStringUtf8();

    }

    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.AccountServiceOuterClass.AddAccountRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.AddAccountRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.AccountServiceOuterClass.AddAccountRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.AddAccountRequest)
        api.gravity.v26.AccountServiceOuterClass.AddAccountRequestOrBuilder {
      // Construct using api.gravity.v26.AccountServiceOuterClass.AddAccountRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string email = 1;</code>
       * @return The email.
       */
      @java.lang.Override
      public java.lang.String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>string email = 1;</code>
       * @return The bytes for email.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>string email = 1;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>string email = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>string email = 1;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      @java.lang.Override
      public java.lang.String getPassword() {
        return instance.getPassword();
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        return instance.getPasswordBytes();
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswordBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.AddAccountRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.AccountServiceOuterClass.AddAccountRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "email_",
              "password_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.AccountServiceOuterClass.AddAccountRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.AccountServiceOuterClass.AddAccountRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.AccountServiceOuterClass.AddAccountRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.AddAccountRequest)
    private static final api.gravity.v26.AccountServiceOuterClass.AddAccountRequest DEFAULT_INSTANCE;
    static {
      AddAccountRequest defaultInstance = new AddAccountRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AddAccountRequest.class, defaultInstance);
    }

    public static api.gravity.v26.AccountServiceOuterClass.AddAccountRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AddAccountRequest> PARSER;

    public static com.google.protobuf.Parser<AddAccountRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AddAccountResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.AddAccountResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     * @return The error.
     */
    api.gravity.types.Types.ErrorInfo getError();
  }
  /**
   * Protobuf type {@code api.gravity.v26.AddAccountResponse}
   */
  public  static final class AddAccountResponse extends
      com.google.protobuf.GeneratedMessageLite<
          AddAccountResponse, AddAccountResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.AddAccountResponse)
      AddAccountResponseOrBuilder {
    private AddAccountResponse() {
      message_ = "";
    }
    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     */
    private void setSuccess(boolean value) {
      
      success_ = value;
    }
    /**
     * <code>bool success = 1;</code>
     */
    private void clearSuccess() {

      success_ = false;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.String message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     */
    private void setMessage(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      message_ = value;
    }
    /**
     * <code>string message = 2;</code>
     */
    private void clearMessage() {

      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();

    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private api.gravity.types.Types.ErrorInfo error_;
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.Override
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.Override
    public api.gravity.types.Types.ErrorInfo getError() {
      return error_ == null ? api.gravity.types.Types.ErrorInfo.getDefaultInstance() : error_;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    private void setError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  error_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  if (error_ != null &&
          error_ != api.gravity.types.Types.ErrorInfo.getDefaultInstance()) {
        error_ =
          api.gravity.types.Types.ErrorInfo.newBuilder(error_).mergeFrom(value).buildPartial();
      } else {
        error_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    private void clearError() {  error_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.AccountServiceOuterClass.AddAccountResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.AddAccountResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.AccountServiceOuterClass.AddAccountResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.AddAccountResponse)
        api.gravity.v26.AccountServiceOuterClass.AddAccountResponseOrBuilder {
      // Construct using api.gravity.v26.AccountServiceOuterClass.AddAccountResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return instance.getSuccess();
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        copyOnWrite();
        instance.setSuccess(value);
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        copyOnWrite();
        instance.clearSuccess();
        return this;
      }

      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      @java.lang.Override
      public java.lang.String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      @java.lang.Override
      public boolean hasError() {
        return instance.hasError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      @java.lang.Override
      public api.gravity.types.Types.ErrorInfo getError() {
        return instance.getError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder setError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.setError(value);
        return this;
        }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder setError(
          api.gravity.types.Types.ErrorInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setError(builderForValue.build());
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder mergeError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.mergeError(value);
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder clearError() {  copyOnWrite();
        instance.clearError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.AddAccountResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.AccountServiceOuterClass.AddAccountResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "success_",
              "message_",
              "error_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0007\u0002\u0208" +
                "\u0003\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.AccountServiceOuterClass.AddAccountResponse> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.AccountServiceOuterClass.AddAccountResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.AccountServiceOuterClass.AddAccountResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.AddAccountResponse)
    private static final api.gravity.v26.AccountServiceOuterClass.AddAccountResponse DEFAULT_INSTANCE;
    static {
      AddAccountResponse defaultInstance = new AddAccountResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AddAccountResponse.class, defaultInstance);
    }

    public static api.gravity.v26.AccountServiceOuterClass.AddAccountResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AddAccountResponse> PARSER;

    public static com.google.protobuf.Parser<AddAccountResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AccountStatusResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.AccountStatusResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool registered = 1;</code>
     * @return The registered.
     */
    boolean getRegistered();

    /**
     * <pre>
     * opcional
     * </pre>
     *
     * <code>string email = 2;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <pre>
     * opcional
     * </pre>
     *
     * <code>string email = 2;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     * @return The error.
     */
    api.gravity.types.Types.ErrorInfo getError();
  }
  /**
   * Protobuf type {@code api.gravity.v26.AccountStatusResponse}
   */
  public  static final class AccountStatusResponse extends
      com.google.protobuf.GeneratedMessageLite<
          AccountStatusResponse, AccountStatusResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.AccountStatusResponse)
      AccountStatusResponseOrBuilder {
    private AccountStatusResponse() {
      email_ = "";
    }
    private int bitField0_;
    public static final int REGISTERED_FIELD_NUMBER = 1;
    private boolean registered_;
    /**
     * <code>bool registered = 1;</code>
     * @return The registered.
     */
    @java.lang.Override
    public boolean getRegistered() {
      return registered_;
    }
    /**
     * <code>bool registered = 1;</code>
     * @param value The registered to set.
     */
    private void setRegistered(boolean value) {
      
      registered_ = value;
    }
    /**
     * <code>bool registered = 1;</code>
     */
    private void clearRegistered() {

      registered_ = false;
    }

    public static final int EMAIL_FIELD_NUMBER = 2;
    private java.lang.String email_;
    /**
     * <pre>
     * opcional
     * </pre>
     *
     * <code>string email = 2;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      return email_;
    }
    /**
     * <pre>
     * opcional
     * </pre>
     *
     * <code>string email = 2;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <pre>
     * opcional
     * </pre>
     *
     * <code>string email = 2;</code>
     * @param value The email to set.
     */
    private void setEmail(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      email_ = value;
    }
    /**
     * <pre>
     * opcional
     * </pre>
     *
     * <code>string email = 2;</code>
     */
    private void clearEmail() {

      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <pre>
     * opcional
     * </pre>
     *
     * <code>string email = 2;</code>
     * @param value The bytes for email to set.
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      email_ = value.toStringUtf8();

    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private api.gravity.types.Types.ErrorInfo error_;
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.Override
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.Override
    public api.gravity.types.Types.ErrorInfo getError() {
      return error_ == null ? api.gravity.types.Types.ErrorInfo.getDefaultInstance() : error_;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    private void setError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  error_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  if (error_ != null &&
          error_ != api.gravity.types.Types.ErrorInfo.getDefaultInstance()) {
        error_ =
          api.gravity.types.Types.ErrorInfo.newBuilder(error_).mergeFrom(value).buildPartial();
      } else {
        error_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    private void clearError() {  error_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.AccountStatusResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.AccountStatusResponse)
        api.gravity.v26.AccountServiceOuterClass.AccountStatusResponseOrBuilder {
      // Construct using api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool registered = 1;</code>
       * @return The registered.
       */
      @java.lang.Override
      public boolean getRegistered() {
        return instance.getRegistered();
      }
      /**
       * <code>bool registered = 1;</code>
       * @param value The registered to set.
       * @return This builder for chaining.
       */
      public Builder setRegistered(boolean value) {
        copyOnWrite();
        instance.setRegistered(value);
        return this;
      }
      /**
       * <code>bool registered = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegistered() {
        copyOnWrite();
        instance.clearRegistered();
        return this;
      }

      /**
       * <pre>
       * opcional
       * </pre>
       *
       * <code>string email = 2;</code>
       * @return The email.
       */
      @java.lang.Override
      public java.lang.String getEmail() {
        return instance.getEmail();
      }
      /**
       * <pre>
       * opcional
       * </pre>
       *
       * <code>string email = 2;</code>
       * @return The bytes for email.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <pre>
       * opcional
       * </pre>
       *
       * <code>string email = 2;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <pre>
       * opcional
       * </pre>
       *
       * <code>string email = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <pre>
       * opcional
       * </pre>
       *
       * <code>string email = 2;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      @java.lang.Override
      public boolean hasError() {
        return instance.hasError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      @java.lang.Override
      public api.gravity.types.Types.ErrorInfo getError() {
        return instance.getError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder setError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.setError(value);
        return this;
        }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder setError(
          api.gravity.types.Types.ErrorInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setError(builderForValue.build());
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder mergeError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.mergeError(value);
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder clearError() {  copyOnWrite();
        instance.clearError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.AccountStatusResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "registered_",
              "email_",
              "error_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0007\u0002\u0208" +
                "\u0003\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.AccountStatusResponse)
    private static final api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse DEFAULT_INSTANCE;
    static {
      AccountStatusResponse defaultInstance = new AccountStatusResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AccountStatusResponse.class, defaultInstance);
    }

    public static api.gravity.v26.AccountServiceOuterClass.AccountStatusResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AccountStatusResponse> PARSER;

    public static com.google.protobuf.Parser<AccountStatusResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RemoveAccountRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.RemoveAccountRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string password = 1;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 1;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code api.gravity.v26.RemoveAccountRequest}
   */
  public  static final class RemoveAccountRequest extends
      com.google.protobuf.GeneratedMessageLite<
          RemoveAccountRequest, RemoveAccountRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.RemoveAccountRequest)
      RemoveAccountRequestOrBuilder {
    private RemoveAccountRequest() {
      password_ = "";
    }
    public static final int PASSWORD_FIELD_NUMBER = 1;
    private java.lang.String password_;
    /**
     * <code>string password = 1;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      return password_;
    }
    /**
     * <code>string password = 1;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(password_);
    }
    /**
     * <code>string password = 1;</code>
     * @param value The password to set.
     */
    private void setPassword(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      password_ = value;
    }
    /**
     * <code>string password = 1;</code>
     */
    private void clearPassword() {

      password_ = getDefaultInstance().getPassword();
    }
    /**
     * <code>string password = 1;</code>
     * @param value The bytes for password to set.
     */
    private void setPasswordBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      password_ = value.toStringUtf8();

    }

    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.RemoveAccountRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.RemoveAccountRequest)
        api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequestOrBuilder {
      // Construct using api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string password = 1;</code>
       * @return The password.
       */
      @java.lang.Override
      public java.lang.String getPassword() {
        return instance.getPassword();
      }
      /**
       * <code>string password = 1;</code>
       * @return The bytes for password.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        return instance.getPasswordBytes();
      }
      /**
       * <code>string password = 1;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <code>string password = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }
      /**
       * <code>string password = 1;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswordBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.RemoveAccountRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "password_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.RemoveAccountRequest)
    private static final api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest DEFAULT_INSTANCE;
    static {
      RemoveAccountRequest defaultInstance = new RemoveAccountRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RemoveAccountRequest.class, defaultInstance);
    }

    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RemoveAccountRequest> PARSER;

    public static com.google.protobuf.Parser<RemoveAccountRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RemoveAccountResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.RemoveAccountResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     * @return The error.
     */
    api.gravity.types.Types.ErrorInfo getError();
  }
  /**
   * Protobuf type {@code api.gravity.v26.RemoveAccountResponse}
   */
  public  static final class RemoveAccountResponse extends
      com.google.protobuf.GeneratedMessageLite<
          RemoveAccountResponse, RemoveAccountResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.RemoveAccountResponse)
      RemoveAccountResponseOrBuilder {
    private RemoveAccountResponse() {
      message_ = "";
    }
    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     */
    private void setSuccess(boolean value) {
      
      success_ = value;
    }
    /**
     * <code>bool success = 1;</code>
     */
    private void clearSuccess() {

      success_ = false;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.String message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     */
    private void setMessage(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      message_ = value;
    }
    /**
     * <code>string message = 2;</code>
     */
    private void clearMessage() {

      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();

    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private api.gravity.types.Types.ErrorInfo error_;
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.Override
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.Override
    public api.gravity.types.Types.ErrorInfo getError() {
      return error_ == null ? api.gravity.types.Types.ErrorInfo.getDefaultInstance() : error_;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    private void setError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  error_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  if (error_ != null &&
          error_ != api.gravity.types.Types.ErrorInfo.getDefaultInstance()) {
        error_ =
          api.gravity.types.Types.ErrorInfo.newBuilder(error_).mergeFrom(value).buildPartial();
      } else {
        error_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    private void clearError() {  error_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.RemoveAccountResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.RemoveAccountResponse)
        api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponseOrBuilder {
      // Construct using api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return instance.getSuccess();
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        copyOnWrite();
        instance.setSuccess(value);
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        copyOnWrite();
        instance.clearSuccess();
        return this;
      }

      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      @java.lang.Override
      public java.lang.String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      @java.lang.Override
      public boolean hasError() {
        return instance.hasError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      @java.lang.Override
      public api.gravity.types.Types.ErrorInfo getError() {
        return instance.getError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder setError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.setError(value);
        return this;
        }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder setError(
          api.gravity.types.Types.ErrorInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setError(builderForValue.build());
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder mergeError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.mergeError(value);
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder clearError() {  copyOnWrite();
        instance.clearError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.RemoveAccountResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "success_",
              "message_",
              "error_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0007\u0002\u0208" +
                "\u0003\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.RemoveAccountResponse)
    private static final api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse DEFAULT_INSTANCE;
    static {
      RemoveAccountResponse defaultInstance = new RemoveAccountResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RemoveAccountResponse.class, defaultInstance);
    }

    public static api.gravity.v26.AccountServiceOuterClass.RemoveAccountResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RemoveAccountResponse> PARSER;

    public static com.google.protobuf.Parser<RemoveAccountResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
