// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_service/v26/event_service.proto
// Protobuf Java Version: 4.26.1

package api.gravity.v26;

public final class EventServiceOuterClass {
  private EventServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   * EventType enumerates all events that Gravity can emit.
   * Values are spaced by category to allow future additions without renumbering.
   * </pre>
   *
   * Protobuf enum {@code api.gravity.v26.EventType}
   */
  public enum EventType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>EVENT_TYPE_UNKNOWN = 0;</code>
     */
    EVENT_TYPE_UNKNOWN(0),
    /**
     * <pre>
     * ── App package lifecycle ────────────────────────────────────────────────
     * </pre>
     *
     * <code>EVENT_APP_INSTALLED = 1;</code>
     */
    EVENT_APP_INSTALLED(1),
    /**
     * <code>EVENT_APP_REMOVED = 2;</code>
     */
    EVENT_APP_REMOVED(2),
    /**
     * <code>EVENT_APP_UPDATED = 3;</code>
     */
    EVENT_APP_UPDATED(3),
    /**
     * <pre>
     * ── App process lifecycle ────────────────────────────────────────────────
     * </pre>
     *
     * <code>EVENT_APP_STARTED = 10;</code>
     */
    EVENT_APP_STARTED(10),
    /**
     * <code>EVENT_APP_STOPPED = 11;</code>
     */
    EVENT_APP_STOPPED(11),
    /**
     * <code>EVENT_APP_CRASHED = 12;</code>
     */
    EVENT_APP_CRASHED(12),
    /**
     * <pre>
     * killed by Attach watchdog
     * </pre>
     *
     * <code>EVENT_APP_REJECTED = 13;</code>
     */
    EVENT_APP_REJECTED(13),
    /**
     * <pre>
     * ── System ───────────────────────────────────────────────────────────────
     * </pre>
     *
     * <code>EVENT_SYSTEM_REBOOT = 20;</code>
     */
    EVENT_SYSTEM_REBOOT(20),
    /**
     * <code>EVENT_SYSTEM_FACTORY_RESET = 21;</code>
     */
    EVENT_SYSTEM_FACTORY_RESET(21),
    /**
     * <code>EVENT_SYSTEM_UPDATE = 22;</code>
     */
    EVENT_SYSTEM_UPDATE(22),
    /**
     * <pre>
     * ── Network ──────────────────────────────────────────────────────────────
     * </pre>
     *
     * <code>EVENT_NET_UP = 30;</code>
     */
    EVENT_NET_UP(30),
    /**
     * <code>EVENT_NET_DOWN = 31;</code>
     */
    EVENT_NET_DOWN(31),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EVENT_TYPE_UNKNOWN = 0;</code>
     */
    public static final int EVENT_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * ── App package lifecycle ────────────────────────────────────────────────
     * </pre>
     *
     * <code>EVENT_APP_INSTALLED = 1;</code>
     */
    public static final int EVENT_APP_INSTALLED_VALUE = 1;
    /**
     * <code>EVENT_APP_REMOVED = 2;</code>
     */
    public static final int EVENT_APP_REMOVED_VALUE = 2;
    /**
     * <code>EVENT_APP_UPDATED = 3;</code>
     */
    public static final int EVENT_APP_UPDATED_VALUE = 3;
    /**
     * <pre>
     * ── App process lifecycle ────────────────────────────────────────────────
     * </pre>
     *
     * <code>EVENT_APP_STARTED = 10;</code>
     */
    public static final int EVENT_APP_STARTED_VALUE = 10;
    /**
     * <code>EVENT_APP_STOPPED = 11;</code>
     */
    public static final int EVENT_APP_STOPPED_VALUE = 11;
    /**
     * <code>EVENT_APP_CRASHED = 12;</code>
     */
    public static final int EVENT_APP_CRASHED_VALUE = 12;
    /**
     * <pre>
     * killed by Attach watchdog
     * </pre>
     *
     * <code>EVENT_APP_REJECTED = 13;</code>
     */
    public static final int EVENT_APP_REJECTED_VALUE = 13;
    /**
     * <pre>
     * ── System ───────────────────────────────────────────────────────────────
     * </pre>
     *
     * <code>EVENT_SYSTEM_REBOOT = 20;</code>
     */
    public static final int EVENT_SYSTEM_REBOOT_VALUE = 20;
    /**
     * <code>EVENT_SYSTEM_FACTORY_RESET = 21;</code>
     */
    public static final int EVENT_SYSTEM_FACTORY_RESET_VALUE = 21;
    /**
     * <code>EVENT_SYSTEM_UPDATE = 22;</code>
     */
    public static final int EVENT_SYSTEM_UPDATE_VALUE = 22;
    /**
     * <pre>
     * ── Network ──────────────────────────────────────────────────────────────
     * </pre>
     *
     * <code>EVENT_NET_UP = 30;</code>
     */
    public static final int EVENT_NET_UP_VALUE = 30;
    /**
     * <code>EVENT_NET_DOWN = 31;</code>
     */
    public static final int EVENT_NET_DOWN_VALUE = 31;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return EVENT_TYPE_UNKNOWN;
        case 1: return EVENT_APP_INSTALLED;
        case 2: return EVENT_APP_REMOVED;
        case 3: return EVENT_APP_UPDATED;
        case 10: return EVENT_APP_STARTED;
        case 11: return EVENT_APP_STOPPED;
        case 12: return EVENT_APP_CRASHED;
        case 13: return EVENT_APP_REJECTED;
        case 20: return EVENT_SYSTEM_REBOOT;
        case 21: return EVENT_SYSTEM_FACTORY_RESET;
        case 22: return EVENT_SYSTEM_UPDATE;
        case 30: return EVENT_NET_UP;
        case 31: return EVENT_NET_DOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            @java.lang.Override
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return EventTypeVerifier.INSTANCE;
    }

    private static final class EventTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new EventTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return EventType.forNumber(number) != null;
            }
          };

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.gravity.v26.EventType)
  }

  public interface SubscribeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.SubscribeRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @return A list containing the types.
     */
    java.util.List<api.gravity.v26.EventServiceOuterClass.EventType> getTypesList();
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @return The count of types.
     */
    int getTypesCount();
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @param index The index of the element to return.
     * @return The types at the given index.
     */
    api.gravity.v26.EventServiceOuterClass.EventType getTypes(int index);
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @return A list containing the enum numeric values on the wire for types.
     */
    java.util.List<java.lang.Integer>
    getTypesValueList();
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of types at the given index.
     */
    int getTypesValue(int index);
  }
  /**
   * Protobuf type {@code api.gravity.v26.SubscribeRequest}
   */
  public  static final class SubscribeRequest extends
      com.google.protobuf.GeneratedMessageLite<
          SubscribeRequest, SubscribeRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.SubscribeRequest)
      SubscribeRequestOrBuilder {
    private SubscribeRequest() {
      types_ = emptyIntList();
    }
    public static final int TYPES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList types_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, api.gravity.v26.EventServiceOuterClass.EventType> types_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, api.gravity.v26.EventServiceOuterClass.EventType>() {
              @java.lang.Override
              public api.gravity.v26.EventServiceOuterClass.EventType convert(java.lang.Integer from) {
                api.gravity.v26.EventServiceOuterClass.EventType result = api.gravity.v26.EventServiceOuterClass.EventType.forNumber(from);
                return result == null ? api.gravity.v26.EventServiceOuterClass.EventType.UNRECOGNIZED : result;
              }
            };
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @return A list containing the types.
     */
    @java.lang.Override
    public java.util.List<api.gravity.v26.EventServiceOuterClass.EventType> getTypesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, api.gravity.v26.EventServiceOuterClass.EventType>(types_, types_converter_);
    }
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @return The count of types.
     */
    @java.lang.Override
    public int getTypesCount() {
      return types_.size();
    }
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @param index The index of the element to return.
     * @return The types at the given index.
     */
    @java.lang.Override
    public api.gravity.v26.EventServiceOuterClass.EventType getTypes(int index) {
      api.gravity.v26.EventServiceOuterClass.EventType result = api.gravity.v26.EventServiceOuterClass.EventType.forNumber(types_.getInt(index));
      return result == null ? api.gravity.v26.EventServiceOuterClass.EventType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @return A list containing the enum numeric values on the wire for types.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getTypesValueList() {
      return types_;
    }
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of types at the given index.
     */
    @java.lang.Override
    public int getTypesValue(int index) {
      return types_.getInt(index);
    }
    private int typesMemoizedSerializedSize;
    private void ensureTypesIsMutable() {
      com.google.protobuf.Internal.IntList tmp = types_;
      if (!tmp.isModifiable()) {
        types_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
      }
    }
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @param index The index to set the value at.
     * @param value The types to set.
     */
    private void setTypes(
        int index, api.gravity.v26.EventServiceOuterClass.EventType value) {
      value.getClass();
  ensureTypesIsMutable();
      types_.setInt(index, value.getNumber());
    }
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @param value The types to add.
     */
    private void addTypes(api.gravity.v26.EventServiceOuterClass.EventType value) {
      value.getClass();
  ensureTypesIsMutable();
      types_.addInt(value.getNumber());
    }
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @param values The types to add.
     */
    private void addAllTypes(
        java.lang.Iterable<? extends api.gravity.v26.EventServiceOuterClass.EventType> values) {
      ensureTypesIsMutable();
      for (api.gravity.v26.EventServiceOuterClass.EventType value : values) {
        types_.addInt(value.getNumber());
      }
    }
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     */
    private void clearTypes() {
      types_ = emptyIntList();
    }
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @param value The enum numeric value on the wire for types to set.
     */
    private void setTypesValue(
        int index, int value) {
      ensureTypesIsMutable();
      types_.setInt(index, value);
    }
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @param value The enum numeric value on the wire for types to add.
     */
    private void addTypesValue(int value) {
      ensureTypesIsMutable();
      types_.addInt(value);
    }
    /**
     * <pre>
     * Event types to subscribe to. Empty = subscribe to all events.
     * </pre>
     *
     * <code>repeated .api.gravity.v26.EventType types = 1;</code>
     * @param values The enum numeric values on the wire for types to add.
     */
    private void addAllTypesValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureTypesIsMutable();
      for (int value : values) {
        types_.addInt(value);
      }
    }

    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.EventServiceOuterClass.SubscribeRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.SubscribeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.EventServiceOuterClass.SubscribeRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.SubscribeRequest)
        api.gravity.v26.EventServiceOuterClass.SubscribeRequestOrBuilder {
      // Construct using api.gravity.v26.EventServiceOuterClass.SubscribeRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @return A list containing the types.
       */
      @java.lang.Override
      public java.util.List<api.gravity.v26.EventServiceOuterClass.EventType> getTypesList() {
        return instance.getTypesList();
      }
      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @return The count of types.
       */
      @java.lang.Override
      public int getTypesCount() {
        return instance.getTypesCount();
      }
      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @param index The index of the element to return.
       * @return The types at the given index.
       */
      @java.lang.Override
      public api.gravity.v26.EventServiceOuterClass.EventType getTypes(int index) {
        return instance.getTypes(index);
      }
      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @param index The index to set the value at.
       * @param value The types to set.
       * @return This builder for chaining.
       */
      public Builder setTypes(
          int index, api.gravity.v26.EventServiceOuterClass.EventType value) {
        copyOnWrite();
        instance.setTypes(index, value);
        return this;
      }
      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @param value The types to add.
       * @return This builder for chaining.
       */
      public Builder addTypes(api.gravity.v26.EventServiceOuterClass.EventType value) {
        copyOnWrite();
        instance.addTypes(value);
        return this;
      }
      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @param values The types to add.
       * @return This builder for chaining.
       */
      public Builder addAllTypes(
          java.lang.Iterable<? extends api.gravity.v26.EventServiceOuterClass.EventType> values) {
        copyOnWrite();
        instance.addAllTypes(values);  return this;
      }
      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypes() {
        copyOnWrite();
        instance.clearTypes();
        return this;
      }
      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @return A list containing the enum numeric values on the wire for types.
       */
      @java.lang.Override
      public java.util.List<java.lang.Integer>
      getTypesValueList() {
        return java.util.Collections.unmodifiableList(
            instance.getTypesValueList());
      }
      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of types at the given index.
       */
      @java.lang.Override
      public int getTypesValue(int index) {
        return instance.getTypesValue(index);
      }
      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @param index The index to set the value at.
       * @param value The enum numeric value on the wire for types to set.
       * @return This builder for chaining.
       */
      public Builder setTypesValue(
          int index, int value) {
        copyOnWrite();
        instance.setTypesValue(index, value);
        return this;
      }
      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @param value The enum numeric value on the wire for types to add.
       * @return This builder for chaining.
       */
      public Builder addTypesValue(int value) {
        copyOnWrite();
        instance.addTypesValue(value);
        return this;
      }
      /**
       * <pre>
       * Event types to subscribe to. Empty = subscribe to all events.
       * </pre>
       *
       * <code>repeated .api.gravity.v26.EventType types = 1;</code>
       * @param values The enum numeric values on the wire for types to add.
       * @return This builder for chaining.
       */
      public Builder addAllTypesValue(
          java.lang.Iterable<java.lang.Integer> values) {
        copyOnWrite();
        instance.addAllTypesValue(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.SubscribeRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.EventServiceOuterClass.SubscribeRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "types_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001,";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.EventServiceOuterClass.SubscribeRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.EventServiceOuterClass.SubscribeRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.EventServiceOuterClass.SubscribeRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.SubscribeRequest)
    private static final api.gravity.v26.EventServiceOuterClass.SubscribeRequest DEFAULT_INSTANCE;
    static {
      SubscribeRequest defaultInstance = new SubscribeRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SubscribeRequest.class, defaultInstance);
    }

    public static api.gravity.v26.EventServiceOuterClass.SubscribeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SubscribeRequest> PARSER;

    public static com.google.protobuf.Parser<SubscribeRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.Event)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * UUID v4
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <pre>
     * UUID v4
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.api.gravity.v26.EventType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.api.gravity.v26.EventType type = 2;</code>
     * @return The type.
     */
    api.gravity.v26.EventServiceOuterClass.EventType getType();

    /**
     * <pre>
     * component that published the event
     * </pre>
     *
     * <code>string source = 3;</code>
     * @return The source.
     */
    java.lang.String getSource();
    /**
     * <pre>
     * component that published the event
     * </pre>
     *
     * <code>string source = 3;</code>
     * @return The bytes for source.
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <pre>
     * Unix nanoseconds
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * JSON — schema is defined per EventType
     * </pre>
     *
     * <code>string payload = 5;</code>
     * @return The payload.
     */
    java.lang.String getPayload();
    /**
     * <pre>
     * JSON — schema is defined per EventType
     * </pre>
     *
     * <code>string payload = 5;</code>
     * @return The bytes for payload.
     */
    com.google.protobuf.ByteString
        getPayloadBytes();
  }
  /**
   * <pre>
   * Event is the generic envelope for all Gravity events.
   * payload is a JSON-encoded string whose schema depends on the event type.
   * </pre>
   *
   * Protobuf type {@code api.gravity.v26.Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessageLite<
          Event, Event.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.Event)
      EventOrBuilder {
    private Event() {
      id_ = "";
      source_ = "";
      payload_ = "";
    }
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.String id_;
    /**
     * <pre>
     * UUID v4
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return id_;
    }
    /**
     * <pre>
     * UUID v4
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(id_);
    }
    /**
     * <pre>
     * UUID v4
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     */
    private void setId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      id_ = value;
    }
    /**
     * <pre>
     * UUID v4
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    private void clearId() {

      id_ = getDefaultInstance().getId();
    }
    /**
     * <pre>
     * UUID v4
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     */
    private void setIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      id_ = value.toStringUtf8();

    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.api.gravity.v26.EventType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.api.gravity.v26.EventType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public api.gravity.v26.EventServiceOuterClass.EventType getType() {
      api.gravity.v26.EventServiceOuterClass.EventType result = api.gravity.v26.EventServiceOuterClass.EventType.forNumber(type_);
      return result == null ? api.gravity.v26.EventServiceOuterClass.EventType.UNRECOGNIZED : result;
    }
    /**
     * <code>.api.gravity.v26.EventType type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     */
    private void setTypeValue(int value) {
        type_ = value;
    }
    /**
     * <code>.api.gravity.v26.EventType type = 2;</code>
     * @param value The type to set.
     */
    private void setType(api.gravity.v26.EventServiceOuterClass.EventType value) {
      type_ = value.getNumber();

    }
    /**
     * <code>.api.gravity.v26.EventType type = 2;</code>
     */
    private void clearType() {

      type_ = 0;
    }

    public static final int SOURCE_FIELD_NUMBER = 3;
    private java.lang.String source_;
    /**
     * <pre>
     * component that published the event
     * </pre>
     *
     * <code>string source = 3;</code>
     * @return The source.
     */
    @java.lang.Override
    public java.lang.String getSource() {
      return source_;
    }
    /**
     * <pre>
     * component that published the event
     * </pre>
     *
     * <code>string source = 3;</code>
     * @return The bytes for source.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(source_);
    }
    /**
     * <pre>
     * component that published the event
     * </pre>
     *
     * <code>string source = 3;</code>
     * @param value The source to set.
     */
    private void setSource(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      source_ = value;
    }
    /**
     * <pre>
     * component that published the event
     * </pre>
     *
     * <code>string source = 3;</code>
     */
    private void clearSource() {

      source_ = getDefaultInstance().getSource();
    }
    /**
     * <pre>
     * component that published the event
     * </pre>
     *
     * <code>string source = 3;</code>
     * @param value The bytes for source to set.
     */
    private void setSourceBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      source_ = value.toStringUtf8();

    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <pre>
     * Unix nanoseconds
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Unix nanoseconds
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <pre>
     * Unix nanoseconds
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     */
    private void clearTimestamp() {

      timestamp_ = 0L;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 5;
    private java.lang.String payload_;
    /**
     * <pre>
     * JSON — schema is defined per EventType
     * </pre>
     *
     * <code>string payload = 5;</code>
     * @return The payload.
     */
    @java.lang.Override
    public java.lang.String getPayload() {
      return payload_;
    }
    /**
     * <pre>
     * JSON — schema is defined per EventType
     * </pre>
     *
     * <code>string payload = 5;</code>
     * @return The bytes for payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(payload_);
    }
    /**
     * <pre>
     * JSON — schema is defined per EventType
     * </pre>
     *
     * <code>string payload = 5;</code>
     * @param value The payload to set.
     */
    private void setPayload(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      payload_ = value;
    }
    /**
     * <pre>
     * JSON — schema is defined per EventType
     * </pre>
     *
     * <code>string payload = 5;</code>
     */
    private void clearPayload() {

      payload_ = getDefaultInstance().getPayload();
    }
    /**
     * <pre>
     * JSON — schema is defined per EventType
     * </pre>
     *
     * <code>string payload = 5;</code>
     * @param value The bytes for payload to set.
     */
    private void setPayloadBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      payload_ = value.toStringUtf8();

    }

    public static api.gravity.v26.EventServiceOuterClass.Event parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.EventServiceOuterClass.Event parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.EventServiceOuterClass.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.EventServiceOuterClass.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.EventServiceOuterClass.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.EventServiceOuterClass.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.EventServiceOuterClass.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.EventServiceOuterClass.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.EventServiceOuterClass.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.EventServiceOuterClass.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.EventServiceOuterClass.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.EventServiceOuterClass.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.EventServiceOuterClass.Event prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Event is the generic envelope for all Gravity events.
     * payload is a JSON-encoded string whose schema depends on the event type.
     * </pre>
     *
     * Protobuf type {@code api.gravity.v26.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.EventServiceOuterClass.Event, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.Event)
        api.gravity.v26.EventServiceOuterClass.EventOrBuilder {
      // Construct using api.gravity.v26.EventServiceOuterClass.Event.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * UUID v4
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        return instance.getId();
      }
      /**
       * <pre>
       * UUID v4
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        return instance.getIdBytes();
      }
      /**
       * <pre>
       * UUID v4
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <pre>
       * UUID v4
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }
      /**
       * <pre>
       * UUID v4
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdBytes(value);
        return this;
      }

      /**
       * <code>.api.gravity.v26.EventType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <code>.api.gravity.v26.EventType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <code>.api.gravity.v26.EventType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public api.gravity.v26.EventServiceOuterClass.EventType getType() {
        return instance.getType();
      }
      /**
       * <code>.api.gravity.v26.EventType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(api.gravity.v26.EventServiceOuterClass.EventType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>.api.gravity.v26.EventType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <pre>
       * component that published the event
       * </pre>
       *
       * <code>string source = 3;</code>
       * @return The source.
       */
      @java.lang.Override
      public java.lang.String getSource() {
        return instance.getSource();
      }
      /**
       * <pre>
       * component that published the event
       * </pre>
       *
       * <code>string source = 3;</code>
       * @return The bytes for source.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSourceBytes() {
        return instance.getSourceBytes();
      }
      /**
       * <pre>
       * component that published the event
       * </pre>
       *
       * <code>string source = 3;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(
          java.lang.String value) {
        copyOnWrite();
        instance.setSource(value);
        return this;
      }
      /**
       * <pre>
       * component that published the event
       * </pre>
       *
       * <code>string source = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        copyOnWrite();
        instance.clearSource();
        return this;
      }
      /**
       * <pre>
       * component that published the event
       * </pre>
       *
       * <code>string source = 3;</code>
       * @param value The bytes for source to set.
       * @return This builder for chaining.
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSourceBytes(value);
        return this;
      }

      /**
       * <pre>
       * Unix nanoseconds
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       * Unix nanoseconds
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * Unix nanoseconds
       * </pre>
       *
       * <code>int64 timestamp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <pre>
       * JSON — schema is defined per EventType
       * </pre>
       *
       * <code>string payload = 5;</code>
       * @return The payload.
       */
      @java.lang.Override
      public java.lang.String getPayload() {
        return instance.getPayload();
      }
      /**
       * <pre>
       * JSON — schema is defined per EventType
       * </pre>
       *
       * <code>string payload = 5;</code>
       * @return The bytes for payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPayloadBytes() {
        return instance.getPayloadBytes();
      }
      /**
       * <pre>
       * JSON — schema is defined per EventType
       * </pre>
       *
       * <code>string payload = 5;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(
          java.lang.String value) {
        copyOnWrite();
        instance.setPayload(value);
        return this;
      }
      /**
       * <pre>
       * JSON — schema is defined per EventType
       * </pre>
       *
       * <code>string payload = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        copyOnWrite();
        instance.clearPayload();
        return this;
      }
      /**
       * <pre>
       * JSON — schema is defined per EventType
       * </pre>
       *
       * <code>string payload = 5;</code>
       * @param value The bytes for payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayloadBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPayloadBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.Event)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.EventServiceOuterClass.Event();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "id_",
              "type_",
              "source_",
              "timestamp_",
              "payload_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\f" +
                "\u0003\u0208\u0004\u0002\u0005\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.EventServiceOuterClass.Event> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.EventServiceOuterClass.Event.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.EventServiceOuterClass.Event>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.Event)
    private static final api.gravity.v26.EventServiceOuterClass.Event DEFAULT_INSTANCE;
    static {
      Event defaultInstance = new Event();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Event.class, defaultInstance);
    }

    public static api.gravity.v26.EventServiceOuterClass.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Event> PARSER;

    public static com.google.protobuf.Parser<Event> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
