// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: power_service/v26/power_service.proto
// Protobuf Java Version: 4.26.1

package api.gravity.v26;

public final class PowerServiceOuterClass {
  private PowerServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code api.gravity.v26.PowerMode}
   */
  public enum PowerMode
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>POWER_MODE_UNSPECIFIED = 0;</code>
     */
    POWER_MODE_UNSPECIFIED(0),
    /**
     * <code>POWER_MODE_NORMAL = 1;</code>
     */
    POWER_MODE_NORMAL(1),
    /**
     * <code>POWER_MODE_LOW_POWER = 2;</code>
     */
    POWER_MODE_LOW_POWER(2),
    /**
     * <code>POWER_MODE_PERFORMANCE = 3;</code>
     */
    POWER_MODE_PERFORMANCE(3),
    /**
     * <code>POWER_MODE_BALANCED = 4;</code>
     */
    POWER_MODE_BALANCED(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>POWER_MODE_UNSPECIFIED = 0;</code>
     */
    public static final int POWER_MODE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>POWER_MODE_NORMAL = 1;</code>
     */
    public static final int POWER_MODE_NORMAL_VALUE = 1;
    /**
     * <code>POWER_MODE_LOW_POWER = 2;</code>
     */
    public static final int POWER_MODE_LOW_POWER_VALUE = 2;
    /**
     * <code>POWER_MODE_PERFORMANCE = 3;</code>
     */
    public static final int POWER_MODE_PERFORMANCE_VALUE = 3;
    /**
     * <code>POWER_MODE_BALANCED = 4;</code>
     */
    public static final int POWER_MODE_BALANCED_VALUE = 4;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PowerMode valueOf(int value) {
      return forNumber(value);
    }

    public static PowerMode forNumber(int value) {
      switch (value) {
        case 0: return POWER_MODE_UNSPECIFIED;
        case 1: return POWER_MODE_NORMAL;
        case 2: return POWER_MODE_LOW_POWER;
        case 3: return POWER_MODE_PERFORMANCE;
        case 4: return POWER_MODE_BALANCED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PowerMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PowerMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PowerMode>() {
            @java.lang.Override
            public PowerMode findValueByNumber(int number) {
              return PowerMode.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return PowerModeVerifier.INSTANCE;
    }

    private static final class PowerModeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PowerModeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return PowerMode.forNumber(number) != null;
            }
          };

    private final int value;

    private PowerMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.gravity.v26.PowerMode)
  }

  public interface RebootRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.RebootRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * If true, forces the reboot immediately
     * </pre>
     *
     * <code>bool force = 1;</code>
     * @return The force.
     */
    boolean getForce();

    /**
     * <pre>
     * Reason for the reboot (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The reason.
     */
    java.lang.String getReason();
    /**
     * <pre>
     * Reason for the reboot (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The bytes for reason.
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * Protobuf type {@code api.gravity.v26.RebootRequest}
   */
  public  static final class RebootRequest extends
      com.google.protobuf.GeneratedMessageLite<
          RebootRequest, RebootRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.RebootRequest)
      RebootRequestOrBuilder {
    private RebootRequest() {
      reason_ = "";
    }
    public static final int FORCE_FIELD_NUMBER = 1;
    private boolean force_;
    /**
     * <pre>
     * If true, forces the reboot immediately
     * </pre>
     *
     * <code>bool force = 1;</code>
     * @return The force.
     */
    @java.lang.Override
    public boolean getForce() {
      return force_;
    }
    /**
     * <pre>
     * If true, forces the reboot immediately
     * </pre>
     *
     * <code>bool force = 1;</code>
     * @param value The force to set.
     */
    private void setForce(boolean value) {
      
      force_ = value;
    }
    /**
     * <pre>
     * If true, forces the reboot immediately
     * </pre>
     *
     * <code>bool force = 1;</code>
     */
    private void clearForce() {

      force_ = false;
    }

    public static final int REASON_FIELD_NUMBER = 2;
    private java.lang.String reason_;
    /**
     * <pre>
     * Reason for the reboot (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      return reason_;
    }
    /**
     * <pre>
     * Reason for the reboot (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(reason_);
    }
    /**
     * <pre>
     * Reason for the reboot (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @param value The reason to set.
     */
    private void setReason(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      reason_ = value;
    }
    /**
     * <pre>
     * Reason for the reboot (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     */
    private void clearReason() {

      reason_ = getDefaultInstance().getReason();
    }
    /**
     * <pre>
     * Reason for the reboot (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @param value The bytes for reason to set.
     */
    private void setReasonBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      reason_ = value.toStringUtf8();

    }

    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.PowerServiceOuterClass.RebootRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.RebootRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.PowerServiceOuterClass.RebootRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.RebootRequest)
        api.gravity.v26.PowerServiceOuterClass.RebootRequestOrBuilder {
      // Construct using api.gravity.v26.PowerServiceOuterClass.RebootRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * If true, forces the reboot immediately
       * </pre>
       *
       * <code>bool force = 1;</code>
       * @return The force.
       */
      @java.lang.Override
      public boolean getForce() {
        return instance.getForce();
      }
      /**
       * <pre>
       * If true, forces the reboot immediately
       * </pre>
       *
       * <code>bool force = 1;</code>
       * @param value The force to set.
       * @return This builder for chaining.
       */
      public Builder setForce(boolean value) {
        copyOnWrite();
        instance.setForce(value);
        return this;
      }
      /**
       * <pre>
       * If true, forces the reboot immediately
       * </pre>
       *
       * <code>bool force = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearForce() {
        copyOnWrite();
        instance.clearForce();
        return this;
      }

      /**
       * <pre>
       * Reason for the reboot (optional)
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @return The reason.
       */
      @java.lang.Override
      public java.lang.String getReason() {
        return instance.getReason();
      }
      /**
       * <pre>
       * Reason for the reboot (optional)
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @return The bytes for reason.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getReasonBytes() {
        return instance.getReasonBytes();
      }
      /**
       * <pre>
       * Reason for the reboot (optional)
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(
          java.lang.String value) {
        copyOnWrite();
        instance.setReason(value);
        return this;
      }
      /**
       * <pre>
       * Reason for the reboot (optional)
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        copyOnWrite();
        instance.clearReason();
        return this;
      }
      /**
       * <pre>
       * Reason for the reboot (optional)
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @param value The bytes for reason to set.
       * @return This builder for chaining.
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setReasonBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.RebootRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.PowerServiceOuterClass.RebootRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "force_",
              "reason_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0007\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.PowerServiceOuterClass.RebootRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.PowerServiceOuterClass.RebootRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.PowerServiceOuterClass.RebootRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.RebootRequest)
    private static final api.gravity.v26.PowerServiceOuterClass.RebootRequest DEFAULT_INSTANCE;
    static {
      RebootRequest defaultInstance = new RebootRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RebootRequest.class, defaultInstance);
    }

    public static api.gravity.v26.PowerServiceOuterClass.RebootRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RebootRequest> PARSER;

    public static com.google.protobuf.Parser<RebootRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ShutdownRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.ShutdownRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * If true, forces the shutdown immediately
     * </pre>
     *
     * <code>bool force = 1;</code>
     * @return The force.
     */
    boolean getForce();

    /**
     * <pre>
     * Reason for the shutdown (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The reason.
     */
    java.lang.String getReason();
    /**
     * <pre>
     * Reason for the shutdown (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The bytes for reason.
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * Protobuf type {@code api.gravity.v26.ShutdownRequest}
   */
  public  static final class ShutdownRequest extends
      com.google.protobuf.GeneratedMessageLite<
          ShutdownRequest, ShutdownRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.ShutdownRequest)
      ShutdownRequestOrBuilder {
    private ShutdownRequest() {
      reason_ = "";
    }
    public static final int FORCE_FIELD_NUMBER = 1;
    private boolean force_;
    /**
     * <pre>
     * If true, forces the shutdown immediately
     * </pre>
     *
     * <code>bool force = 1;</code>
     * @return The force.
     */
    @java.lang.Override
    public boolean getForce() {
      return force_;
    }
    /**
     * <pre>
     * If true, forces the shutdown immediately
     * </pre>
     *
     * <code>bool force = 1;</code>
     * @param value The force to set.
     */
    private void setForce(boolean value) {
      
      force_ = value;
    }
    /**
     * <pre>
     * If true, forces the shutdown immediately
     * </pre>
     *
     * <code>bool force = 1;</code>
     */
    private void clearForce() {

      force_ = false;
    }

    public static final int REASON_FIELD_NUMBER = 2;
    private java.lang.String reason_;
    /**
     * <pre>
     * Reason for the shutdown (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      return reason_;
    }
    /**
     * <pre>
     * Reason for the shutdown (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(reason_);
    }
    /**
     * <pre>
     * Reason for the shutdown (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @param value The reason to set.
     */
    private void setReason(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      reason_ = value;
    }
    /**
     * <pre>
     * Reason for the shutdown (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     */
    private void clearReason() {

      reason_ = getDefaultInstance().getReason();
    }
    /**
     * <pre>
     * Reason for the shutdown (optional)
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @param value The bytes for reason to set.
     */
    private void setReasonBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      reason_ = value.toStringUtf8();

    }

    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.PowerServiceOuterClass.ShutdownRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.ShutdownRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.PowerServiceOuterClass.ShutdownRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.ShutdownRequest)
        api.gravity.v26.PowerServiceOuterClass.ShutdownRequestOrBuilder {
      // Construct using api.gravity.v26.PowerServiceOuterClass.ShutdownRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * If true, forces the shutdown immediately
       * </pre>
       *
       * <code>bool force = 1;</code>
       * @return The force.
       */
      @java.lang.Override
      public boolean getForce() {
        return instance.getForce();
      }
      /**
       * <pre>
       * If true, forces the shutdown immediately
       * </pre>
       *
       * <code>bool force = 1;</code>
       * @param value The force to set.
       * @return This builder for chaining.
       */
      public Builder setForce(boolean value) {
        copyOnWrite();
        instance.setForce(value);
        return this;
      }
      /**
       * <pre>
       * If true, forces the shutdown immediately
       * </pre>
       *
       * <code>bool force = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearForce() {
        copyOnWrite();
        instance.clearForce();
        return this;
      }

      /**
       * <pre>
       * Reason for the shutdown (optional)
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @return The reason.
       */
      @java.lang.Override
      public java.lang.String getReason() {
        return instance.getReason();
      }
      /**
       * <pre>
       * Reason for the shutdown (optional)
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @return The bytes for reason.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getReasonBytes() {
        return instance.getReasonBytes();
      }
      /**
       * <pre>
       * Reason for the shutdown (optional)
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(
          java.lang.String value) {
        copyOnWrite();
        instance.setReason(value);
        return this;
      }
      /**
       * <pre>
       * Reason for the shutdown (optional)
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        copyOnWrite();
        instance.clearReason();
        return this;
      }
      /**
       * <pre>
       * Reason for the shutdown (optional)
       * </pre>
       *
       * <code>string reason = 2;</code>
       * @param value The bytes for reason to set.
       * @return This builder for chaining.
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setReasonBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.ShutdownRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.PowerServiceOuterClass.ShutdownRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "force_",
              "reason_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0007\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.PowerServiceOuterClass.ShutdownRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.PowerServiceOuterClass.ShutdownRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.PowerServiceOuterClass.ShutdownRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.ShutdownRequest)
    private static final api.gravity.v26.PowerServiceOuterClass.ShutdownRequest DEFAULT_INSTANCE;
    static {
      ShutdownRequest defaultInstance = new ShutdownRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ShutdownRequest.class, defaultInstance);
    }

    public static api.gravity.v26.PowerServiceOuterClass.ShutdownRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ShutdownRequest> PARSER;

    public static com.google.protobuf.Parser<ShutdownRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
