// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor_service/v26/sensor_service.proto
// Protobuf Java Version: 4.26.1

package api.gravity.v26;

public final class SensorServiceOuterClass {
  private SensorServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CapabilitiesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.CapabilitiesResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @return A list containing the sensorTypes.
     */
    java.util.List<java.lang.String>
        getSensorTypesList();
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @return The count of sensorTypes.
     */
    int getSensorTypesCount();
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param index The index of the element to return.
     * @return The sensorTypes at the given index.
     */
    java.lang.String getSensorTypes(int index);
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param index The index of the element to return.
     * @return The sensorTypes at the given index.
     */
    com.google.protobuf.ByteString
        getSensorTypesBytes(int index);

    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     * @return The error.
     */
    api.gravity.types.Types.ErrorInfo getError();
  }
  /**
   * <pre>
   * Response for GetCapabilities
   * </pre>
   *
   * Protobuf type {@code api.gravity.v26.CapabilitiesResponse}
   */
  public  static final class CapabilitiesResponse extends
      com.google.protobuf.GeneratedMessageLite<
          CapabilitiesResponse, CapabilitiesResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.CapabilitiesResponse)
      CapabilitiesResponseOrBuilder {
    private CapabilitiesResponse() {
      sensorTypes_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    private int bitField0_;
    public static final int SENSOR_TYPES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> sensorTypes_;
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @return A list containing the sensorTypes.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getSensorTypesList() {
      return sensorTypes_;
    }
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @return The count of sensorTypes.
     */
    @java.lang.Override
    public int getSensorTypesCount() {
      return sensorTypes_.size();
    }
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param index The index of the element to return.
     * @return The sensorTypes at the given index.
     */
    @java.lang.Override
    public java.lang.String getSensorTypes(int index) {
      return sensorTypes_.get(index);
    }
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sensorTypes at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSensorTypesBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          sensorTypes_.get(index));
    }
    private void ensureSensorTypesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
          sensorTypes_;  if (!tmp.isModifiable()) {
        sensorTypes_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param index The index to set the value at.
     * @param value The sensorTypes to set.
     */
    private void setSensorTypes(
        int index, java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureSensorTypesIsMutable();
      sensorTypes_.set(index, value);
    }
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param value The sensorTypes to add.
     */
    private void addSensorTypes(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureSensorTypesIsMutable();
      sensorTypes_.add(value);
    }
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param values The sensorTypes to add.
     */
    private void addAllSensorTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureSensorTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, sensorTypes_);
    }
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     */
    private void clearSensorTypes() {
      sensorTypes_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <pre>
     * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param value The bytes of the sensorTypes to add.
     */
    private void addSensorTypesBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ensureSensorTypesIsMutable();
      sensorTypes_.add(value.toStringUtf8());
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private api.gravity.types.Types.ErrorInfo error_;
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    @java.lang.Override
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    @java.lang.Override
    public api.gravity.types.Types.ErrorInfo getError() {
      return error_ == null ? api.gravity.types.Types.ErrorInfo.getDefaultInstance() : error_;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    private void setError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  error_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  if (error_ != null &&
          error_ != api.gravity.types.Types.ErrorInfo.getDefaultInstance()) {
        error_ =
          api.gravity.types.Types.ErrorInfo.newBuilder(error_).mergeFrom(value).buildPartial();
      } else {
        error_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    private void clearError() {  error_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Response for GetCapabilities
     * </pre>
     *
     * Protobuf type {@code api.gravity.v26.CapabilitiesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.CapabilitiesResponse)
        api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponseOrBuilder {
      // Construct using api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @return A list containing the sensorTypes.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getSensorTypesList() {
        return java.util.Collections.unmodifiableList(
            instance.getSensorTypesList());
      }
      /**
       * <pre>
       * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @return The count of sensorTypes.
       */
      @java.lang.Override
      public int getSensorTypesCount() {
        return instance.getSensorTypesCount();
      }
      /**
       * <pre>
       * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param index The index of the element to return.
       * @return The sensorTypes at the given index.
       */
      @java.lang.Override
      public java.lang.String getSensorTypes(int index) {
        return instance.getSensorTypes(index);
      }
      /**
       * <pre>
       * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the sensorTypes at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSensorTypesBytes(int index) {
        return instance.getSensorTypesBytes(index);
      }
      /**
       * <pre>
       * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param index The index to set the value at.
       * @param value The sensorTypes to set.
       * @return This builder for chaining.
       */
      public Builder setSensorTypes(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setSensorTypes(index, value);
        return this;
      }
      /**
       * <pre>
       * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param value The sensorTypes to add.
       * @return This builder for chaining.
       */
      public Builder addSensorTypes(
          java.lang.String value) {
        copyOnWrite();
        instance.addSensorTypes(value);
        return this;
      }
      /**
       * <pre>
       * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param values The sensorTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllSensorTypes(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllSensorTypes(values);
        return this;
      }
      /**
       * <pre>
       * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSensorTypes() {
        copyOnWrite();
        instance.clearSensorTypes();
        return this;
      }
      /**
       * <pre>
       * List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param value The bytes of the sensorTypes to add.
       * @return This builder for chaining.
       */
      public Builder addSensorTypesBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addSensorTypesBytes(value);
        return this;
      }

      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      @java.lang.Override
      public boolean hasError() {
        return instance.hasError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      @java.lang.Override
      public api.gravity.types.Types.ErrorInfo getError() {
        return instance.getError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder setError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.setError(value);
        return this;
        }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder setError(
          api.gravity.types.Types.ErrorInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setError(builderForValue.build());
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder mergeError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.mergeError(value);
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder clearError() {  copyOnWrite();
        instance.clearError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.CapabilitiesResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "sensorTypes_",
              "error_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u021a\u0002\u1009" +
                "\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.CapabilitiesResponse)
    private static final api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse DEFAULT_INSTANCE;
    static {
      CapabilitiesResponse defaultInstance = new CapabilitiesResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CapabilitiesResponse.class, defaultInstance);
    }

    public static api.gravity.v26.SensorServiceOuterClass.CapabilitiesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CapabilitiesResponse> PARSER;

    public static com.google.protobuf.Parser<CapabilitiesResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SensorEventsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.SensorEventsRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @return A list containing the sensorTypes.
     */
    java.util.List<java.lang.String>
        getSensorTypesList();
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @return The count of sensorTypes.
     */
    int getSensorTypesCount();
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param index The index of the element to return.
     * @return The sensorTypes at the given index.
     */
    java.lang.String getSensorTypes(int index);
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param index The index of the element to return.
     * @return The sensorTypes at the given index.
     */
    com.google.protobuf.ByteString
        getSensorTypesBytes(int index);
  }
  /**
   * <pre>
   * Request for SubscribeSensorEvents
   * </pre>
   *
   * Protobuf type {@code api.gravity.v26.SensorEventsRequest}
   */
  public  static final class SensorEventsRequest extends
      com.google.protobuf.GeneratedMessageLite<
          SensorEventsRequest, SensorEventsRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.SensorEventsRequest)
      SensorEventsRequestOrBuilder {
    private SensorEventsRequest() {
      sensorTypes_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    public static final int SENSOR_TYPES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> sensorTypes_;
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @return A list containing the sensorTypes.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getSensorTypesList() {
      return sensorTypes_;
    }
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @return The count of sensorTypes.
     */
    @java.lang.Override
    public int getSensorTypesCount() {
      return sensorTypes_.size();
    }
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param index The index of the element to return.
     * @return The sensorTypes at the given index.
     */
    @java.lang.Override
    public java.lang.String getSensorTypes(int index) {
      return sensorTypes_.get(index);
    }
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sensorTypes at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSensorTypesBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          sensorTypes_.get(index));
    }
    private void ensureSensorTypesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
          sensorTypes_;  if (!tmp.isModifiable()) {
        sensorTypes_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param index The index to set the value at.
     * @param value The sensorTypes to set.
     */
    private void setSensorTypes(
        int index, java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureSensorTypesIsMutable();
      sensorTypes_.set(index, value);
    }
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param value The sensorTypes to add.
     */
    private void addSensorTypes(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureSensorTypesIsMutable();
      sensorTypes_.add(value);
    }
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param values The sensorTypes to add.
     */
    private void addAllSensorTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureSensorTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, sensorTypes_);
    }
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     */
    private void clearSensorTypes() {
      sensorTypes_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <pre>
     * Optional: filter by sensor type (empty = all)
     * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
     * </pre>
     *
     * <code>repeated string sensor_types = 1;</code>
     * @param value The bytes of the sensorTypes to add.
     */
    private void addSensorTypesBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ensureSensorTypesIsMutable();
      sensorTypes_.add(value.toStringUtf8());
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Request for SubscribeSensorEvents
     * </pre>
     *
     * Protobuf type {@code api.gravity.v26.SensorEventsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.SensorEventsRequest)
        api.gravity.v26.SensorServiceOuterClass.SensorEventsRequestOrBuilder {
      // Construct using api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Optional: filter by sensor type (empty = all)
       * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @return A list containing the sensorTypes.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getSensorTypesList() {
        return java.util.Collections.unmodifiableList(
            instance.getSensorTypesList());
      }
      /**
       * <pre>
       * Optional: filter by sensor type (empty = all)
       * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @return The count of sensorTypes.
       */
      @java.lang.Override
      public int getSensorTypesCount() {
        return instance.getSensorTypesCount();
      }
      /**
       * <pre>
       * Optional: filter by sensor type (empty = all)
       * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param index The index of the element to return.
       * @return The sensorTypes at the given index.
       */
      @java.lang.Override
      public java.lang.String getSensorTypes(int index) {
        return instance.getSensorTypes(index);
      }
      /**
       * <pre>
       * Optional: filter by sensor type (empty = all)
       * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the sensorTypes at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSensorTypesBytes(int index) {
        return instance.getSensorTypesBytes(index);
      }
      /**
       * <pre>
       * Optional: filter by sensor type (empty = all)
       * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param index The index to set the value at.
       * @param value The sensorTypes to set.
       * @return This builder for chaining.
       */
      public Builder setSensorTypes(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setSensorTypes(index, value);
        return this;
      }
      /**
       * <pre>
       * Optional: filter by sensor type (empty = all)
       * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param value The sensorTypes to add.
       * @return This builder for chaining.
       */
      public Builder addSensorTypes(
          java.lang.String value) {
        copyOnWrite();
        instance.addSensorTypes(value);
        return this;
      }
      /**
       * <pre>
       * Optional: filter by sensor type (empty = all)
       * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param values The sensorTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllSensorTypes(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllSensorTypes(values);
        return this;
      }
      /**
       * <pre>
       * Optional: filter by sensor type (empty = all)
       * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSensorTypes() {
        copyOnWrite();
        instance.clearSensorTypes();
        return this;
      }
      /**
       * <pre>
       * Optional: filter by sensor type (empty = all)
       * Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
       * </pre>
       *
       * <code>repeated string sensor_types = 1;</code>
       * @param value The bytes of the sensorTypes to add.
       * @return This builder for chaining.
       */
      public Builder addSensorTypesBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addSensorTypesBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.SensorEventsRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "sensorTypes_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u021a";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.SensorEventsRequest)
    private static final api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest DEFAULT_INSTANCE;
    static {
      SensorEventsRequest defaultInstance = new SensorEventsRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SensorEventsRequest.class, defaultInstance);
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEventsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SensorEventsRequest> PARSER;

    public static com.google.protobuf.Parser<SensorEventsRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SensorEventResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.SensorEventResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.api.gravity.v26.SensorEvent event = 1;</code>
     * @return Whether the event field is set.
     */
    boolean hasEvent();
    /**
     * <code>.api.gravity.v26.SensorEvent event = 1;</code>
     * @return The event.
     */
    api.gravity.v26.SensorServiceOuterClass.SensorEvent getEvent();

    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     * @return The error.
     */
    api.gravity.types.Types.ErrorInfo getError();
  }
  /**
   * <pre>
   * Response for sensor events
   * </pre>
   *
   * Protobuf type {@code api.gravity.v26.SensorEventResponse}
   */
  public  static final class SensorEventResponse extends
      com.google.protobuf.GeneratedMessageLite<
          SensorEventResponse, SensorEventResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.SensorEventResponse)
      SensorEventResponseOrBuilder {
    private SensorEventResponse() {
    }
    private int bitField0_;
    public static final int EVENT_FIELD_NUMBER = 1;
    private api.gravity.v26.SensorServiceOuterClass.SensorEvent event_;
    /**
     * <code>.api.gravity.v26.SensorEvent event = 1;</code>
     */
    @java.lang.Override
    public boolean hasEvent() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.api.gravity.v26.SensorEvent event = 1;</code>
     */
    @java.lang.Override
    public api.gravity.v26.SensorServiceOuterClass.SensorEvent getEvent() {
      return event_ == null ? api.gravity.v26.SensorServiceOuterClass.SensorEvent.getDefaultInstance() : event_;
    }
    /**
     * <code>.api.gravity.v26.SensorEvent event = 1;</code>
     */
    private void setEvent(api.gravity.v26.SensorServiceOuterClass.SensorEvent value) {
      value.getClass();
  event_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.api.gravity.v26.SensorEvent event = 1;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeEvent(api.gravity.v26.SensorServiceOuterClass.SensorEvent value) {
      value.getClass();
  if (event_ != null &&
          event_ != api.gravity.v26.SensorServiceOuterClass.SensorEvent.getDefaultInstance()) {
        event_ =
          api.gravity.v26.SensorServiceOuterClass.SensorEvent.newBuilder(event_).mergeFrom(value).buildPartial();
      } else {
        event_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.api.gravity.v26.SensorEvent event = 1;</code>
     */
    private void clearEvent() {  event_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private api.gravity.types.Types.ErrorInfo error_;
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    @java.lang.Override
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    @java.lang.Override
    public api.gravity.types.Types.ErrorInfo getError() {
      return error_ == null ? api.gravity.types.Types.ErrorInfo.getDefaultInstance() : error_;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    private void setError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  error_ = value;
      bitField0_ |= 0x00000002;
      }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  if (error_ != null &&
          error_ != api.gravity.types.Types.ErrorInfo.getDefaultInstance()) {
        error_ =
          api.gravity.types.Types.ErrorInfo.newBuilder(error_).mergeFrom(value).buildPartial();
      } else {
        error_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    private void clearError() {  error_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.SensorServiceOuterClass.SensorEventResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Response for sensor events
     * </pre>
     *
     * Protobuf type {@code api.gravity.v26.SensorEventResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.SensorServiceOuterClass.SensorEventResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.SensorEventResponse)
        api.gravity.v26.SensorServiceOuterClass.SensorEventResponseOrBuilder {
      // Construct using api.gravity.v26.SensorServiceOuterClass.SensorEventResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.api.gravity.v26.SensorEvent event = 1;</code>
       */
      @java.lang.Override
      public boolean hasEvent() {
        return instance.hasEvent();
      }
      /**
       * <code>.api.gravity.v26.SensorEvent event = 1;</code>
       */
      @java.lang.Override
      public api.gravity.v26.SensorServiceOuterClass.SensorEvent getEvent() {
        return instance.getEvent();
      }
      /**
       * <code>.api.gravity.v26.SensorEvent event = 1;</code>
       */
      public Builder setEvent(api.gravity.v26.SensorServiceOuterClass.SensorEvent value) {
        copyOnWrite();
        instance.setEvent(value);
        return this;
        }
      /**
       * <code>.api.gravity.v26.SensorEvent event = 1;</code>
       */
      public Builder setEvent(
          api.gravity.v26.SensorServiceOuterClass.SensorEvent.Builder builderForValue) {
        copyOnWrite();
        instance.setEvent(builderForValue.build());
        return this;
      }
      /**
       * <code>.api.gravity.v26.SensorEvent event = 1;</code>
       */
      public Builder mergeEvent(api.gravity.v26.SensorServiceOuterClass.SensorEvent value) {
        copyOnWrite();
        instance.mergeEvent(value);
        return this;
      }
      /**
       * <code>.api.gravity.v26.SensorEvent event = 1;</code>
       */
      public Builder clearEvent() {  copyOnWrite();
        instance.clearEvent();
        return this;
      }

      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      @java.lang.Override
      public boolean hasError() {
        return instance.hasError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      @java.lang.Override
      public api.gravity.types.Types.ErrorInfo getError() {
        return instance.getError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder setError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.setError(value);
        return this;
        }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder setError(
          api.gravity.types.Types.ErrorInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setError(builderForValue.build());
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder mergeError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.mergeError(value);
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder clearError() {  copyOnWrite();
        instance.clearError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.SensorEventResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.SensorServiceOuterClass.SensorEventResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "event_",
              "error_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
                "\u1009\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.SensorServiceOuterClass.SensorEventResponse> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.SensorServiceOuterClass.SensorEventResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.SensorServiceOuterClass.SensorEventResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.SensorEventResponse)
    private static final api.gravity.v26.SensorServiceOuterClass.SensorEventResponse DEFAULT_INSTANCE;
    static {
      SensorEventResponse defaultInstance = new SensorEventResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SensorEventResponse.class, defaultInstance);
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEventResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SensorEventResponse> PARSER;

    public static com.google.protobuf.Parser<SensorEventResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SensorEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.SensorEvent)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Event timestamp (Unix timestamp in milliseconds)
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
     * </pre>
     *
     * <code>string sensor_type = 2;</code>
     * @return The sensorType.
     */
    java.lang.String getSensorType();
    /**
     * <pre>
     * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
     * </pre>
     *
     * <code>string sensor_type = 2;</code>
     * @return The bytes for sensorType.
     */
    com.google.protobuf.ByteString
        getSensorTypeBytes();

    /**
     * <pre>
     * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
     * </pre>
     *
     * <code>string sensor_name = 3;</code>
     * @return The sensorName.
     */
    java.lang.String getSensorName();
    /**
     * <pre>
     * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
     * </pre>
     *
     * <code>string sensor_name = 3;</code>
     * @return The bytes for sensorName.
     */
    com.google.protobuf.ByteString
        getSensorNameBytes();

    /**
     * <pre>
     * Array of sensor values (generic)
     * Examples:
     * - Temperature: [45.2]
     * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
     * - Multiple temperatures: [45.2, 50.1, 48.3]
     * </pre>
     *
     * <code>repeated double values = 4;</code>
     * @return A list containing the values.
     */
    java.util.List<java.lang.Double> getValuesList();
    /**
     * <pre>
     * Array of sensor values (generic)
     * Examples:
     * - Temperature: [45.2]
     * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
     * - Multiple temperatures: [45.2, 50.1, 48.3]
     * </pre>
     *
     * <code>repeated double values = 4;</code>
     * @return The count of values.
     */
    int getValuesCount();
    /**
     * <pre>
     * Array of sensor values (generic)
     * Examples:
     * - Temperature: [45.2]
     * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
     * - Multiple temperatures: [45.2, 50.1, 48.3]
     * </pre>
     *
     * <code>repeated double values = 4;</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    double getValues(int index);

    /**
     * <pre>
     * Metadata describing how to interpret the values
     * Examples:
     * - Temperature: {"format": "[ºC]", "unit": "celsius"}
     * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
     * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
     * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */
    int getMetadataCount();
    /**
     * <pre>
     * Metadata describing how to interpret the values
     * Examples:
     * - Temperature: {"format": "[ºC]", "unit": "celsius"}
     * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
     * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
     * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */
    boolean containsMetadata(
        java.lang.String key);
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMetadata();
    /**
     * <pre>
     * Metadata describing how to interpret the values
     * Examples:
     * - Temperature: {"format": "[ºC]", "unit": "celsius"}
     * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
     * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
     * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMetadataMap();
    /**
     * <pre>
     * Metadata describing how to interpret the values
     * Examples:
     * - Temperature: {"format": "[ºC]", "unit": "celsius"}
     * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
     * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
     * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */

    /* nullable */
java.lang.String getMetadataOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <pre>
     * Metadata describing how to interpret the values
     * Examples:
     * - Temperature: {"format": "[ºC]", "unit": "celsius"}
     * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
     * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
     * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */

    java.lang.String getMetadataOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * Sensor event
   * </pre>
   *
   * Protobuf type {@code api.gravity.v26.SensorEvent}
   */
  public  static final class SensorEvent extends
      com.google.protobuf.GeneratedMessageLite<
          SensorEvent, SensorEvent.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.SensorEvent)
      SensorEventOrBuilder {
    private SensorEvent() {
      sensorType_ = "";
      sensorName_ = "";
      values_ = emptyDoubleList();
    }
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <pre>
     * Event timestamp (Unix timestamp in milliseconds)
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Event timestamp (Unix timestamp in milliseconds)
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <pre>
     * Event timestamp (Unix timestamp in milliseconds)
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    private void clearTimestamp() {

      timestamp_ = 0L;
    }

    public static final int SENSOR_TYPE_FIELD_NUMBER = 2;
    private java.lang.String sensorType_;
    /**
     * <pre>
     * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
     * </pre>
     *
     * <code>string sensor_type = 2;</code>
     * @return The sensorType.
     */
    @java.lang.Override
    public java.lang.String getSensorType() {
      return sensorType_;
    }
    /**
     * <pre>
     * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
     * </pre>
     *
     * <code>string sensor_type = 2;</code>
     * @return The bytes for sensorType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSensorTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sensorType_);
    }
    /**
     * <pre>
     * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
     * </pre>
     *
     * <code>string sensor_type = 2;</code>
     * @param value The sensorType to set.
     */
    private void setSensorType(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      sensorType_ = value;
    }
    /**
     * <pre>
     * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
     * </pre>
     *
     * <code>string sensor_type = 2;</code>
     */
    private void clearSensorType() {

      sensorType_ = getDefaultInstance().getSensorType();
    }
    /**
     * <pre>
     * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
     * </pre>
     *
     * <code>string sensor_type = 2;</code>
     * @param value The bytes for sensorType to set.
     */
    private void setSensorTypeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      sensorType_ = value.toStringUtf8();

    }

    public static final int SENSOR_NAME_FIELD_NUMBER = 3;
    private java.lang.String sensorName_;
    /**
     * <pre>
     * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
     * </pre>
     *
     * <code>string sensor_name = 3;</code>
     * @return The sensorName.
     */
    @java.lang.Override
    public java.lang.String getSensorName() {
      return sensorName_;
    }
    /**
     * <pre>
     * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
     * </pre>
     *
     * <code>string sensor_name = 3;</code>
     * @return The bytes for sensorName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSensorNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sensorName_);
    }
    /**
     * <pre>
     * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
     * </pre>
     *
     * <code>string sensor_name = 3;</code>
     * @param value The sensorName to set.
     */
    private void setSensorName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      sensorName_ = value;
    }
    /**
     * <pre>
     * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
     * </pre>
     *
     * <code>string sensor_name = 3;</code>
     */
    private void clearSensorName() {

      sensorName_ = getDefaultInstance().getSensorName();
    }
    /**
     * <pre>
     * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
     * </pre>
     *
     * <code>string sensor_name = 3;</code>
     * @param value The bytes for sensorName to set.
     */
    private void setSensorNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      sensorName_ = value.toStringUtf8();

    }

    public static final int VALUES_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.DoubleList values_;
    /**
     * <pre>
     * Array of sensor values (generic)
     * Examples:
     * - Temperature: [45.2]
     * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
     * - Multiple temperatures: [45.2, 50.1, 48.3]
     * </pre>
     *
     * <code>repeated double values = 4;</code>
     * @return A list containing the values.
     */
    @java.lang.Override
    public java.util.List<java.lang.Double>
        getValuesList() {
      return values_;
    }
    /**
     * <pre>
     * Array of sensor values (generic)
     * Examples:
     * - Temperature: [45.2]
     * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
     * - Multiple temperatures: [45.2, 50.1, 48.3]
     * </pre>
     *
     * <code>repeated double values = 4;</code>
     * @return The count of values.
     */
    @java.lang.Override
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <pre>
     * Array of sensor values (generic)
     * Examples:
     * - Temperature: [45.2]
     * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
     * - Multiple temperatures: [45.2, 50.1, 48.3]
     * </pre>
     *
     * <code>repeated double values = 4;</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    @java.lang.Override
    public double getValues(int index) {
      return values_.getDouble(index);
    }
    private int valuesMemoizedSerializedSize = -1;
    private void ensureValuesIsMutable() {
      com.google.protobuf.Internal.DoubleList tmp = values_;
      if (!tmp.isModifiable()) {
        values_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <pre>
     * Array of sensor values (generic)
     * Examples:
     * - Temperature: [45.2]
     * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
     * - Multiple temperatures: [45.2, 50.1, 48.3]
     * </pre>
     *
     * <code>repeated double values = 4;</code>
     * @param index The index to set the value at.
     * @param value The values to set.
     */
    private void setValues(
        int index, double value) {
      ensureValuesIsMutable();
      values_.setDouble(index, value);
    }
    /**
     * <pre>
     * Array of sensor values (generic)
     * Examples:
     * - Temperature: [45.2]
     * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
     * - Multiple temperatures: [45.2, 50.1, 48.3]
     * </pre>
     *
     * <code>repeated double values = 4;</code>
     * @param value The values to add.
     */
    private void addValues(double value) {
      ensureValuesIsMutable();
      values_.addDouble(value);
    }
    /**
     * <pre>
     * Array of sensor values (generic)
     * Examples:
     * - Temperature: [45.2]
     * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
     * - Multiple temperatures: [45.2, 50.1, 48.3]
     * </pre>
     *
     * <code>repeated double values = 4;</code>
     * @param values The values to add.
     */
    private void addAllValues(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, values_);
    }
    /**
     * <pre>
     * Array of sensor values (generic)
     * Examples:
     * - Temperature: [45.2]
     * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
     * - Multiple temperatures: [45.2, 50.1, 48.3]
     * </pre>
     *
     * <code>repeated double values = 4;</code>
     */
    private void clearValues() {
      values_ = emptyDoubleList();
    }

    public static final int METADATA_FIELD_NUMBER = 5;
    private static final class MetadataDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, java.lang.String> metadata_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetMetadata() {
      return metadata_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetMutableMetadata() {
      if (!metadata_.isMutable()) {
        metadata_ = metadata_.mutableCopy();
      }
      return metadata_;
    }
    @java.lang.Override

    public int getMetadataCount() {
      return internalGetMetadata().size();
    }
    /**
     * <pre>
     * Metadata describing how to interpret the values
     * Examples:
     * - Temperature: {"format": "[ºC]", "unit": "celsius"}
     * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
     * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
     * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */
    @java.lang.Override

    public boolean containsMetadata(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return internalGetMetadata().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <pre>
     * Metadata describing how to interpret the values
     * Examples:
     * - Temperature: {"format": "[ºC]", "unit": "celsius"}
     * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
     * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
     * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetMetadata());
    }
    /**
     * <pre>
     * Metadata describing how to interpret the values
     * Examples:
     * - Temperature: {"format": "[ºC]", "unit": "celsius"}
     * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
     * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
     * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */
    @java.lang.Override

    public /* nullable */
java.lang.String getMetadataOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Metadata describing how to interpret the values
     * Examples:
     * - Temperature: {"format": "[ºC]", "unit": "celsius"}
     * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
     * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
     * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getMetadataOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <pre>
     * Metadata describing how to interpret the values
     * Examples:
     * - Temperature: {"format": "[ºC]", "unit": "celsius"}
     * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
     * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
     * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */
    private java.util.Map<java.lang.String, java.lang.String>
    getMutableMetadataMap() {
      return internalGetMutableMetadata();
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.SensorServiceOuterClass.SensorEvent prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Sensor event
     * </pre>
     *
     * Protobuf type {@code api.gravity.v26.SensorEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.SensorServiceOuterClass.SensorEvent, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.SensorEvent)
        api.gravity.v26.SensorServiceOuterClass.SensorEventOrBuilder {
      // Construct using api.gravity.v26.SensorServiceOuterClass.SensorEvent.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Event timestamp (Unix timestamp in milliseconds)
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       * Event timestamp (Unix timestamp in milliseconds)
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * Event timestamp (Unix timestamp in milliseconds)
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <pre>
       * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
       * </pre>
       *
       * <code>string sensor_type = 2;</code>
       * @return The sensorType.
       */
      @java.lang.Override
      public java.lang.String getSensorType() {
        return instance.getSensorType();
      }
      /**
       * <pre>
       * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
       * </pre>
       *
       * <code>string sensor_type = 2;</code>
       * @return The bytes for sensorType.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSensorTypeBytes() {
        return instance.getSensorTypeBytes();
      }
      /**
       * <pre>
       * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
       * </pre>
       *
       * <code>string sensor_type = 2;</code>
       * @param value The sensorType to set.
       * @return This builder for chaining.
       */
      public Builder setSensorType(
          java.lang.String value) {
        copyOnWrite();
        instance.setSensorType(value);
        return this;
      }
      /**
       * <pre>
       * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
       * </pre>
       *
       * <code>string sensor_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSensorType() {
        copyOnWrite();
        instance.clearSensorType();
        return this;
      }
      /**
       * <pre>
       * Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
       * </pre>
       *
       * <code>string sensor_type = 2;</code>
       * @param value The bytes for sensorType to set.
       * @return This builder for chaining.
       */
      public Builder setSensorTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSensorTypeBytes(value);
        return this;
      }

      /**
       * <pre>
       * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
       * </pre>
       *
       * <code>string sensor_name = 3;</code>
       * @return The sensorName.
       */
      @java.lang.Override
      public java.lang.String getSensorName() {
        return instance.getSensorName();
      }
      /**
       * <pre>
       * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
       * </pre>
       *
       * <code>string sensor_name = 3;</code>
       * @return The bytes for sensorName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSensorNameBytes() {
        return instance.getSensorNameBytes();
      }
      /**
       * <pre>
       * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
       * </pre>
       *
       * <code>string sensor_name = 3;</code>
       * @param value The sensorName to set.
       * @return This builder for chaining.
       */
      public Builder setSensorName(
          java.lang.String value) {
        copyOnWrite();
        instance.setSensorName(value);
        return this;
      }
      /**
       * <pre>
       * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
       * </pre>
       *
       * <code>string sensor_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSensorName() {
        copyOnWrite();
        instance.clearSensorName();
        return this;
      }
      /**
       * <pre>
       * Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
       * </pre>
       *
       * <code>string sensor_name = 3;</code>
       * @param value The bytes for sensorName to set.
       * @return This builder for chaining.
       */
      public Builder setSensorNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSensorNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * Array of sensor values (generic)
       * Examples:
       * - Temperature: [45.2]
       * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
       * - Multiple temperatures: [45.2, 50.1, 48.3]
       * </pre>
       *
       * <code>repeated double values = 4;</code>
       * @return A list containing the values.
       */
      @java.lang.Override
      public java.util.List<java.lang.Double>
          getValuesList() {
        return java.util.Collections.unmodifiableList(
            instance.getValuesList());
      }
      /**
       * <pre>
       * Array of sensor values (generic)
       * Examples:
       * - Temperature: [45.2]
       * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
       * - Multiple temperatures: [45.2, 50.1, 48.3]
       * </pre>
       *
       * <code>repeated double values = 4;</code>
       * @return The count of values.
       */
      @java.lang.Override
      public int getValuesCount() {
        return instance.getValuesCount();
      }
      /**
       * <pre>
       * Array of sensor values (generic)
       * Examples:
       * - Temperature: [45.2]
       * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
       * - Multiple temperatures: [45.2, 50.1, 48.3]
       * </pre>
       *
       * <code>repeated double values = 4;</code>
       * @param index The index of the element to return.
       * @return The values at the given index.
       */
      @java.lang.Override
      public double getValues(int index) {
        return instance.getValues(index);
      }
      /**
       * <pre>
       * Array of sensor values (generic)
       * Examples:
       * - Temperature: [45.2]
       * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
       * - Multiple temperatures: [45.2, 50.1, 48.3]
       * </pre>
       *
       * <code>repeated double values = 4;</code>
       * @param value The values to set.
       * @return This builder for chaining.
       */
      public Builder setValues(
          int index, double value) {
        copyOnWrite();
        instance.setValues(index, value);
        return this;
      }
      /**
       * <pre>
       * Array of sensor values (generic)
       * Examples:
       * - Temperature: [45.2]
       * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
       * - Multiple temperatures: [45.2, 50.1, 48.3]
       * </pre>
       *
       * <code>repeated double values = 4;</code>
       * @param value The values to add.
       * @return This builder for chaining.
       */
      public Builder addValues(double value) {
        copyOnWrite();
        instance.addValues(value);
        return this;
      }
      /**
       * <pre>
       * Array of sensor values (generic)
       * Examples:
       * - Temperature: [45.2]
       * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
       * - Multiple temperatures: [45.2, 50.1, 48.3]
       * </pre>
       *
       * <code>repeated double values = 4;</code>
       * @param values The values to add.
       * @return This builder for chaining.
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends java.lang.Double> values) {
        copyOnWrite();
        instance.addAllValues(values);
        return this;
      }
      /**
       * <pre>
       * Array of sensor values (generic)
       * Examples:
       * - Temperature: [45.2]
       * - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
       * - Multiple temperatures: [45.2, 50.1, 48.3]
       * </pre>
       *
       * <code>repeated double values = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValues() {
        copyOnWrite();
        instance.clearValues();
        return this;
      }

      @java.lang.Override

      public int getMetadataCount() {
        return instance.getMetadataMap().size();
      }
      /**
       * <pre>
       * Metadata describing how to interpret the values
       * Examples:
       * - Temperature: {"format": "[ºC]", "unit": "celsius"}
       * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
       * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
       * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 5;</code>
       */
      @java.lang.Override

      public boolean containsMetadata(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        return instance.getMetadataMap().containsKey(key);
      }

      public Builder clearMetadata() {
        copyOnWrite();
        instance.getMutableMetadataMap().clear();
        return this;
      }
      /**
       * <pre>
       * Metadata describing how to interpret the values
       * Examples:
       * - Temperature: {"format": "[ºC]", "unit": "celsius"}
       * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
       * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
       * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 5;</code>
       */

      public Builder removeMetadata(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        copyOnWrite();
        instance.getMutableMetadataMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getMetadataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
        return getMetadataMap();
      }
      /**
       * <pre>
       * Metadata describing how to interpret the values
       * Examples:
       * - Temperature: {"format": "[ºC]", "unit": "celsius"}
       * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
       * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
       * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 5;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getMetadataMap());
      }
      /**
       * <pre>
       * Metadata describing how to interpret the values
       * Examples:
       * - Temperature: {"format": "[ºC]", "unit": "celsius"}
       * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
       * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
       * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 5;</code>
       */
      @java.lang.Override

      public /* nullable */
java.lang.String getMetadataOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getMetadataMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Metadata describing how to interpret the values
       * Examples:
       * - Temperature: {"format": "[ºC]", "unit": "celsius"}
       * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
       * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
       * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 5;</code>
       */
      @java.lang.Override

      public java.lang.String getMetadataOrThrow(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getMetadataMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <pre>
       * Metadata describing how to interpret the values
       * Examples:
       * - Temperature: {"format": "[ºC]", "unit": "celsius"}
       * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
       * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
       * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 5;</code>
       */
      public Builder putMetadata(
          java.lang.String key,
          java.lang.String value) {
        java.lang.Class<?> keyClass = key.getClass();
        java.lang.Class<?> valueClass = value.getClass();
        copyOnWrite();
        instance.getMutableMetadataMap().put(key, value);
        return this;
      }
      /**
       * <pre>
       * Metadata describing how to interpret the values
       * Examples:
       * - Temperature: {"format": "[ºC]", "unit": "celsius"}
       * - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
       * - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
       * - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 5;</code>
       */
      public Builder putAllMetadata(
          java.util.Map<java.lang.String, java.lang.String> values) {
        copyOnWrite();
        instance.getMutableMetadataMap().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.SensorEvent)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.SensorServiceOuterClass.SensorEvent();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timestamp_",
              "sensorType_",
              "sensorName_",
              "values_",
              "metadata_",
              MetadataDefaultEntryHolder.defaultEntry,
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0001\u0001\u0000\u0001\u0002\u0002\u0208" +
                "\u0003\u0208\u0004#\u00052";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.SensorServiceOuterClass.SensorEvent> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.SensorServiceOuterClass.SensorEvent.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.SensorServiceOuterClass.SensorEvent>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.SensorEvent)
    private static final api.gravity.v26.SensorServiceOuterClass.SensorEvent DEFAULT_INSTANCE;
    static {
      SensorEvent defaultInstance = new SensorEvent();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SensorEvent.class, defaultInstance);
    }

    public static api.gravity.v26.SensorServiceOuterClass.SensorEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SensorEvent> PARSER;

    public static com.google.protobuf.Parser<SensorEvent> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
