// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: time_service/v26/time_service.proto
// Protobuf Java Version: 4.26.1

package api.gravity.v26;

public final class TimeServiceOuterClass {
  private TimeServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NTPConfigRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.NTPConfigRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool enabled = 1;</code>
     * @return The enabled.
     */
    boolean getEnabled();

    /**
     * <code>repeated string servers = 2;</code>
     * @return A list containing the servers.
     */
    java.util.List<java.lang.String>
        getServersList();
    /**
     * <code>repeated string servers = 2;</code>
     * @return The count of servers.
     */
    int getServersCount();
    /**
     * <code>repeated string servers = 2;</code>
     * @param index The index of the element to return.
     * @return The servers at the given index.
     */
    java.lang.String getServers(int index);
    /**
     * <code>repeated string servers = 2;</code>
     * @param index The index of the element to return.
     * @return The servers at the given index.
     */
    com.google.protobuf.ByteString
        getServersBytes(int index);

    /**
     * <pre>
     * Write NTP time to hardware clock
     * </pre>
     *
     * <code>bool rtc_sync = 3;</code>
     * @return The rtcSync.
     */
    boolean getRtcSync();
  }
  /**
   * <pre>
   * Atomic NTP configuration
   * </pre>
   *
   * Protobuf type {@code api.gravity.v26.NTPConfigRequest}
   */
  public  static final class NTPConfigRequest extends
      com.google.protobuf.GeneratedMessageLite<
          NTPConfigRequest, NTPConfigRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.NTPConfigRequest)
      NTPConfigRequestOrBuilder {
    private NTPConfigRequest() {
      servers_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    public static final int ENABLED_FIELD_NUMBER = 1;
    private boolean enabled_;
    /**
     * <code>bool enabled = 1;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }
    /**
     * <code>bool enabled = 1;</code>
     * @param value The enabled to set.
     */
    private void setEnabled(boolean value) {
      
      enabled_ = value;
    }
    /**
     * <code>bool enabled = 1;</code>
     */
    private void clearEnabled() {

      enabled_ = false;
    }

    public static final int SERVERS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> servers_;
    /**
     * <code>repeated string servers = 2;</code>
     * @return A list containing the servers.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getServersList() {
      return servers_;
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @return The count of servers.
     */
    @java.lang.Override
    public int getServersCount() {
      return servers_.size();
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param index The index of the element to return.
     * @return The servers at the given index.
     */
    @java.lang.Override
    public java.lang.String getServers(int index) {
      return servers_.get(index);
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the servers at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServersBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          servers_.get(index));
    }
    private void ensureServersIsMutable() {
      com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
          servers_;  if (!tmp.isModifiable()) {
        servers_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param index The index to set the value at.
     * @param value The servers to set.
     */
    private void setServers(
        int index, java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureServersIsMutable();
      servers_.set(index, value);
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param value The servers to add.
     */
    private void addServers(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureServersIsMutable();
      servers_.add(value);
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param values The servers to add.
     */
    private void addAllServers(
        java.lang.Iterable<java.lang.String> values) {
      ensureServersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, servers_);
    }
    /**
     * <code>repeated string servers = 2;</code>
     */
    private void clearServers() {
      servers_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param value The bytes of the servers to add.
     */
    private void addServersBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ensureServersIsMutable();
      servers_.add(value.toStringUtf8());
    }

    public static final int RTC_SYNC_FIELD_NUMBER = 3;
    private boolean rtcSync_;
    /**
     * <pre>
     * Write NTP time to hardware clock
     * </pre>
     *
     * <code>bool rtc_sync = 3;</code>
     * @return The rtcSync.
     */
    @java.lang.Override
    public boolean getRtcSync() {
      return rtcSync_;
    }
    /**
     * <pre>
     * Write NTP time to hardware clock
     * </pre>
     *
     * <code>bool rtc_sync = 3;</code>
     * @param value The rtcSync to set.
     */
    private void setRtcSync(boolean value) {
      
      rtcSync_ = value;
    }
    /**
     * <pre>
     * Write NTP time to hardware clock
     * </pre>
     *
     * <code>bool rtc_sync = 3;</code>
     */
    private void clearRtcSync() {

      rtcSync_ = false;
    }

    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Atomic NTP configuration
     * </pre>
     *
     * Protobuf type {@code api.gravity.v26.NTPConfigRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.NTPConfigRequest)
        api.gravity.v26.TimeServiceOuterClass.NTPConfigRequestOrBuilder {
      // Construct using api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool enabled = 1;</code>
       * @return The enabled.
       */
      @java.lang.Override
      public boolean getEnabled() {
        return instance.getEnabled();
      }
      /**
       * <code>bool enabled = 1;</code>
       * @param value The enabled to set.
       * @return This builder for chaining.
       */
      public Builder setEnabled(boolean value) {
        copyOnWrite();
        instance.setEnabled(value);
        return this;
      }
      /**
       * <code>bool enabled = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnabled() {
        copyOnWrite();
        instance.clearEnabled();
        return this;
      }

      /**
       * <code>repeated string servers = 2;</code>
       * @return A list containing the servers.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getServersList() {
        return java.util.Collections.unmodifiableList(
            instance.getServersList());
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @return The count of servers.
       */
      @java.lang.Override
      public int getServersCount() {
        return instance.getServersCount();
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param index The index of the element to return.
       * @return The servers at the given index.
       */
      @java.lang.Override
      public java.lang.String getServers(int index) {
        return instance.getServers(index);
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the servers at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getServersBytes(int index) {
        return instance.getServersBytes(index);
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param index The index to set the value at.
       * @param value The servers to set.
       * @return This builder for chaining.
       */
      public Builder setServers(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setServers(index, value);
        return this;
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param value The servers to add.
       * @return This builder for chaining.
       */
      public Builder addServers(
          java.lang.String value) {
        copyOnWrite();
        instance.addServers(value);
        return this;
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param values The servers to add.
       * @return This builder for chaining.
       */
      public Builder addAllServers(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllServers(values);
        return this;
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServers() {
        copyOnWrite();
        instance.clearServers();
        return this;
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param value The bytes of the servers to add.
       * @return This builder for chaining.
       */
      public Builder addServersBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addServersBytes(value);
        return this;
      }

      /**
       * <pre>
       * Write NTP time to hardware clock
       * </pre>
       *
       * <code>bool rtc_sync = 3;</code>
       * @return The rtcSync.
       */
      @java.lang.Override
      public boolean getRtcSync() {
        return instance.getRtcSync();
      }
      /**
       * <pre>
       * Write NTP time to hardware clock
       * </pre>
       *
       * <code>bool rtc_sync = 3;</code>
       * @param value The rtcSync to set.
       * @return This builder for chaining.
       */
      public Builder setRtcSync(boolean value) {
        copyOnWrite();
        instance.setRtcSync(value);
        return this;
      }
      /**
       * <pre>
       * Write NTP time to hardware clock
       * </pre>
       *
       * <code>bool rtc_sync = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtcSync() {
        copyOnWrite();
        instance.clearRtcSync();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.NTPConfigRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "enabled_",
              "servers_",
              "rtcSync_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0007\u0002\u021a" +
                "\u0003\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.NTPConfigRequest)
    private static final api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest DEFAULT_INSTANCE;
    static {
      NTPConfigRequest defaultInstance = new NTPConfigRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NTPConfigRequest.class, defaultInstance);
    }

    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NTPConfigRequest> PARSER;

    public static com.google.protobuf.Parser<NTPConfigRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NTPConfigResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.NTPConfigResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool enabled = 1;</code>
     * @return The enabled.
     */
    boolean getEnabled();

    /**
     * <code>repeated string servers = 2;</code>
     * @return A list containing the servers.
     */
    java.util.List<java.lang.String>
        getServersList();
    /**
     * <code>repeated string servers = 2;</code>
     * @return The count of servers.
     */
    int getServersCount();
    /**
     * <code>repeated string servers = 2;</code>
     * @param index The index of the element to return.
     * @return The servers at the given index.
     */
    java.lang.String getServers(int index);
    /**
     * <code>repeated string servers = 2;</code>
     * @param index The index of the element to return.
     * @return The servers at the given index.
     */
    com.google.protobuf.ByteString
        getServersBytes(int index);

    /**
     * <code>bool rtc_sync = 3;</code>
     * @return The rtcSync.
     */
    boolean getRtcSync();

    /**
     * <code>.api.gravity.types.ErrorInfo error = 4;</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.api.gravity.types.ErrorInfo error = 4;</code>
     * @return The error.
     */
    api.gravity.types.Types.ErrorInfo getError();
  }
  /**
   * Protobuf type {@code api.gravity.v26.NTPConfigResponse}
   */
  public  static final class NTPConfigResponse extends
      com.google.protobuf.GeneratedMessageLite<
          NTPConfigResponse, NTPConfigResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.NTPConfigResponse)
      NTPConfigResponseOrBuilder {
    private NTPConfigResponse() {
      servers_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    private int bitField0_;
    public static final int ENABLED_FIELD_NUMBER = 1;
    private boolean enabled_;
    /**
     * <code>bool enabled = 1;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }
    /**
     * <code>bool enabled = 1;</code>
     * @param value The enabled to set.
     */
    private void setEnabled(boolean value) {
      
      enabled_ = value;
    }
    /**
     * <code>bool enabled = 1;</code>
     */
    private void clearEnabled() {

      enabled_ = false;
    }

    public static final int SERVERS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> servers_;
    /**
     * <code>repeated string servers = 2;</code>
     * @return A list containing the servers.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getServersList() {
      return servers_;
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @return The count of servers.
     */
    @java.lang.Override
    public int getServersCount() {
      return servers_.size();
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param index The index of the element to return.
     * @return The servers at the given index.
     */
    @java.lang.Override
    public java.lang.String getServers(int index) {
      return servers_.get(index);
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the servers at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServersBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          servers_.get(index));
    }
    private void ensureServersIsMutable() {
      com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
          servers_;  if (!tmp.isModifiable()) {
        servers_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param index The index to set the value at.
     * @param value The servers to set.
     */
    private void setServers(
        int index, java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureServersIsMutable();
      servers_.set(index, value);
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param value The servers to add.
     */
    private void addServers(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureServersIsMutable();
      servers_.add(value);
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param values The servers to add.
     */
    private void addAllServers(
        java.lang.Iterable<java.lang.String> values) {
      ensureServersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, servers_);
    }
    /**
     * <code>repeated string servers = 2;</code>
     */
    private void clearServers() {
      servers_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string servers = 2;</code>
     * @param value The bytes of the servers to add.
     */
    private void addServersBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ensureServersIsMutable();
      servers_.add(value.toStringUtf8());
    }

    public static final int RTC_SYNC_FIELD_NUMBER = 3;
    private boolean rtcSync_;
    /**
     * <code>bool rtc_sync = 3;</code>
     * @return The rtcSync.
     */
    @java.lang.Override
    public boolean getRtcSync() {
      return rtcSync_;
    }
    /**
     * <code>bool rtc_sync = 3;</code>
     * @param value The rtcSync to set.
     */
    private void setRtcSync(boolean value) {
      
      rtcSync_ = value;
    }
    /**
     * <code>bool rtc_sync = 3;</code>
     */
    private void clearRtcSync() {

      rtcSync_ = false;
    }

    public static final int ERROR_FIELD_NUMBER = 4;
    private api.gravity.types.Types.ErrorInfo error_;
    /**
     * <code>.api.gravity.types.ErrorInfo error = 4;</code>
     */
    @java.lang.Override
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 4;</code>
     */
    @java.lang.Override
    public api.gravity.types.Types.ErrorInfo getError() {
      return error_ == null ? api.gravity.types.Types.ErrorInfo.getDefaultInstance() : error_;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 4;</code>
     */
    private void setError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  error_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 4;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  if (error_ != null &&
          error_ != api.gravity.types.Types.ErrorInfo.getDefaultInstance()) {
        error_ =
          api.gravity.types.Types.ErrorInfo.newBuilder(error_).mergeFrom(value).buildPartial();
      } else {
        error_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 4;</code>
     */
    private void clearError() {  error_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.NTPConfigResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.NTPConfigResponse)
        api.gravity.v26.TimeServiceOuterClass.NTPConfigResponseOrBuilder {
      // Construct using api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool enabled = 1;</code>
       * @return The enabled.
       */
      @java.lang.Override
      public boolean getEnabled() {
        return instance.getEnabled();
      }
      /**
       * <code>bool enabled = 1;</code>
       * @param value The enabled to set.
       * @return This builder for chaining.
       */
      public Builder setEnabled(boolean value) {
        copyOnWrite();
        instance.setEnabled(value);
        return this;
      }
      /**
       * <code>bool enabled = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnabled() {
        copyOnWrite();
        instance.clearEnabled();
        return this;
      }

      /**
       * <code>repeated string servers = 2;</code>
       * @return A list containing the servers.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getServersList() {
        return java.util.Collections.unmodifiableList(
            instance.getServersList());
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @return The count of servers.
       */
      @java.lang.Override
      public int getServersCount() {
        return instance.getServersCount();
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param index The index of the element to return.
       * @return The servers at the given index.
       */
      @java.lang.Override
      public java.lang.String getServers(int index) {
        return instance.getServers(index);
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the servers at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getServersBytes(int index) {
        return instance.getServersBytes(index);
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param index The index to set the value at.
       * @param value The servers to set.
       * @return This builder for chaining.
       */
      public Builder setServers(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setServers(index, value);
        return this;
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param value The servers to add.
       * @return This builder for chaining.
       */
      public Builder addServers(
          java.lang.String value) {
        copyOnWrite();
        instance.addServers(value);
        return this;
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param values The servers to add.
       * @return This builder for chaining.
       */
      public Builder addAllServers(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllServers(values);
        return this;
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServers() {
        copyOnWrite();
        instance.clearServers();
        return this;
      }
      /**
       * <code>repeated string servers = 2;</code>
       * @param value The bytes of the servers to add.
       * @return This builder for chaining.
       */
      public Builder addServersBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addServersBytes(value);
        return this;
      }

      /**
       * <code>bool rtc_sync = 3;</code>
       * @return The rtcSync.
       */
      @java.lang.Override
      public boolean getRtcSync() {
        return instance.getRtcSync();
      }
      /**
       * <code>bool rtc_sync = 3;</code>
       * @param value The rtcSync to set.
       * @return This builder for chaining.
       */
      public Builder setRtcSync(boolean value) {
        copyOnWrite();
        instance.setRtcSync(value);
        return this;
      }
      /**
       * <code>bool rtc_sync = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtcSync() {
        copyOnWrite();
        instance.clearRtcSync();
        return this;
      }

      /**
       * <code>.api.gravity.types.ErrorInfo error = 4;</code>
       */
      @java.lang.Override
      public boolean hasError() {
        return instance.hasError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 4;</code>
       */
      @java.lang.Override
      public api.gravity.types.Types.ErrorInfo getError() {
        return instance.getError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 4;</code>
       */
      public Builder setError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.setError(value);
        return this;
        }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 4;</code>
       */
      public Builder setError(
          api.gravity.types.Types.ErrorInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setError(builderForValue.build());
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 4;</code>
       */
      public Builder mergeError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.mergeError(value);
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 4;</code>
       */
      public Builder clearError() {  copyOnWrite();
        instance.clearError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.NTPConfigResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "enabled_",
              "servers_",
              "rtcSync_",
              "error_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0001\u0000\u0001\u0007\u0002\u021a" +
                "\u0003\u0007\u0004\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.NTPConfigResponse)
    private static final api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse DEFAULT_INSTANCE;
    static {
      NTPConfigResponse defaultInstance = new NTPConfigResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        NTPConfigResponse.class, defaultInstance);
    }

    public static api.gravity.v26.TimeServiceOuterClass.NTPConfigResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NTPConfigResponse> PARSER;

    public static com.google.protobuf.Parser<NTPConfigResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetTimeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.GetTimeResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 time = 1;</code>
     * @return The time.
     */
    long getTime();

    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     * @return The error.
     */
    api.gravity.types.Types.ErrorInfo getError();
  }
  /**
   * Protobuf type {@code api.gravity.v26.GetTimeResponse}
   */
  public  static final class GetTimeResponse extends
      com.google.protobuf.GeneratedMessageLite<
          GetTimeResponse, GetTimeResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.GetTimeResponse)
      GetTimeResponseOrBuilder {
    private GetTimeResponse() {
    }
    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>int64 time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }
    /**
     * <code>int64 time = 1;</code>
     * @param value The time to set.
     */
    private void setTime(long value) {
      
      time_ = value;
    }
    /**
     * <code>int64 time = 1;</code>
     */
    private void clearTime() {

      time_ = 0L;
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private api.gravity.types.Types.ErrorInfo error_;
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    @java.lang.Override
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    @java.lang.Override
    public api.gravity.types.Types.ErrorInfo getError() {
      return error_ == null ? api.gravity.types.Types.ErrorInfo.getDefaultInstance() : error_;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    private void setError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  error_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  if (error_ != null &&
          error_ != api.gravity.types.Types.ErrorInfo.getDefaultInstance()) {
        error_ =
          api.gravity.types.Types.ErrorInfo.newBuilder(error_).mergeFrom(value).buildPartial();
      } else {
        error_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 2;</code>
     */
    private void clearError() {  error_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.TimeServiceOuterClass.GetTimeResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.GetTimeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.TimeServiceOuterClass.GetTimeResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.GetTimeResponse)
        api.gravity.v26.TimeServiceOuterClass.GetTimeResponseOrBuilder {
      // Construct using api.gravity.v26.TimeServiceOuterClass.GetTimeResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 time = 1;</code>
       * @return The time.
       */
      @java.lang.Override
      public long getTime() {
        return instance.getTime();
      }
      /**
       * <code>int64 time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        copyOnWrite();
        instance.setTime(value);
        return this;
      }
      /**
       * <code>int64 time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        copyOnWrite();
        instance.clearTime();
        return this;
      }

      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      @java.lang.Override
      public boolean hasError() {
        return instance.hasError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      @java.lang.Override
      public api.gravity.types.Types.ErrorInfo getError() {
        return instance.getError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder setError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.setError(value);
        return this;
        }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder setError(
          api.gravity.types.Types.ErrorInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setError(builderForValue.build());
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder mergeError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.mergeError(value);
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 2;</code>
       */
      public Builder clearError() {  copyOnWrite();
        instance.clearError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.GetTimeResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.TimeServiceOuterClass.GetTimeResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "time_",
              "error_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\u1009" +
                "\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.TimeServiceOuterClass.GetTimeResponse> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.TimeServiceOuterClass.GetTimeResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.TimeServiceOuterClass.GetTimeResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.GetTimeResponse)
    private static final api.gravity.v26.TimeServiceOuterClass.GetTimeResponse DEFAULT_INSTANCE;
    static {
      GetTimeResponse defaultInstance = new GetTimeResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetTimeResponse.class, defaultInstance);
    }

    public static api.gravity.v26.TimeServiceOuterClass.GetTimeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetTimeResponse> PARSER;

    public static com.google.protobuf.Parser<GetTimeResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SetTimeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.SetTimeRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 time = 1;</code>
     * @return The time.
     */
    long getTime();
  }
  /**
   * Protobuf type {@code api.gravity.v26.SetTimeRequest}
   */
  public  static final class SetTimeRequest extends
      com.google.protobuf.GeneratedMessageLite<
          SetTimeRequest, SetTimeRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.SetTimeRequest)
      SetTimeRequestOrBuilder {
    private SetTimeRequest() {
    }
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>int64 time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }
    /**
     * <code>int64 time = 1;</code>
     * @param value The time to set.
     */
    private void setTime(long value) {
      
      time_ = value;
    }
    /**
     * <code>int64 time = 1;</code>
     */
    private void clearTime() {

      time_ = 0L;
    }

    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.TimeServiceOuterClass.SetTimeRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.SetTimeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.TimeServiceOuterClass.SetTimeRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.SetTimeRequest)
        api.gravity.v26.TimeServiceOuterClass.SetTimeRequestOrBuilder {
      // Construct using api.gravity.v26.TimeServiceOuterClass.SetTimeRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 time = 1;</code>
       * @return The time.
       */
      @java.lang.Override
      public long getTime() {
        return instance.getTime();
      }
      /**
       * <code>int64 time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        copyOnWrite();
        instance.setTime(value);
        return this;
      }
      /**
       * <code>int64 time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        copyOnWrite();
        instance.clearTime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.SetTimeRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.TimeServiceOuterClass.SetTimeRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "time_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.TimeServiceOuterClass.SetTimeRequest> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.TimeServiceOuterClass.SetTimeRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.TimeServiceOuterClass.SetTimeRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.SetTimeRequest)
    private static final api.gravity.v26.TimeServiceOuterClass.SetTimeRequest DEFAULT_INSTANCE;
    static {
      SetTimeRequest defaultInstance = new SetTimeRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SetTimeRequest.class, defaultInstance);
    }

    public static api.gravity.v26.TimeServiceOuterClass.SetTimeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SetTimeRequest> PARSER;

    public static com.google.protobuf.Parser<SetTimeRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UptimeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.UptimeResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 uptime_sec = 1;</code>
     * @return The uptimeSec.
     */
    long getUptimeSec();

    /**
     * <code>int64 uptime_millis = 2;</code>
     * @return The uptimeMillis.
     */
    long getUptimeMillis();

    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     * @return The error.
     */
    api.gravity.types.Types.ErrorInfo getError();
  }
  /**
   * Protobuf type {@code api.gravity.v26.UptimeResponse}
   */
  public  static final class UptimeResponse extends
      com.google.protobuf.GeneratedMessageLite<
          UptimeResponse, UptimeResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.UptimeResponse)
      UptimeResponseOrBuilder {
    private UptimeResponse() {
    }
    private int bitField0_;
    public static final int UPTIME_SEC_FIELD_NUMBER = 1;
    private long uptimeSec_;
    /**
     * <code>int64 uptime_sec = 1;</code>
     * @return The uptimeSec.
     */
    @java.lang.Override
    public long getUptimeSec() {
      return uptimeSec_;
    }
    /**
     * <code>int64 uptime_sec = 1;</code>
     * @param value The uptimeSec to set.
     */
    private void setUptimeSec(long value) {
      
      uptimeSec_ = value;
    }
    /**
     * <code>int64 uptime_sec = 1;</code>
     */
    private void clearUptimeSec() {

      uptimeSec_ = 0L;
    }

    public static final int UPTIME_MILLIS_FIELD_NUMBER = 2;
    private long uptimeMillis_;
    /**
     * <code>int64 uptime_millis = 2;</code>
     * @return The uptimeMillis.
     */
    @java.lang.Override
    public long getUptimeMillis() {
      return uptimeMillis_;
    }
    /**
     * <code>int64 uptime_millis = 2;</code>
     * @param value The uptimeMillis to set.
     */
    private void setUptimeMillis(long value) {
      
      uptimeMillis_ = value;
    }
    /**
     * <code>int64 uptime_millis = 2;</code>
     */
    private void clearUptimeMillis() {

      uptimeMillis_ = 0L;
    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private api.gravity.types.Types.ErrorInfo error_;
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.Override
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.Override
    public api.gravity.types.Types.ErrorInfo getError() {
      return error_ == null ? api.gravity.types.Types.ErrorInfo.getDefaultInstance() : error_;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    private void setError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  error_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeError(api.gravity.types.Types.ErrorInfo value) {
      value.getClass();
  if (error_ != null &&
          error_ != api.gravity.types.Types.ErrorInfo.getDefaultInstance()) {
        error_ =
          api.gravity.types.Types.ErrorInfo.newBuilder(error_).mergeFrom(value).buildPartial();
      } else {
        error_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.api.gravity.types.ErrorInfo error = 3;</code>
     */
    private void clearError() {  error_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.TimeServiceOuterClass.UptimeResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.UptimeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.TimeServiceOuterClass.UptimeResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.UptimeResponse)
        api.gravity.v26.TimeServiceOuterClass.UptimeResponseOrBuilder {
      // Construct using api.gravity.v26.TimeServiceOuterClass.UptimeResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 uptime_sec = 1;</code>
       * @return The uptimeSec.
       */
      @java.lang.Override
      public long getUptimeSec() {
        return instance.getUptimeSec();
      }
      /**
       * <code>int64 uptime_sec = 1;</code>
       * @param value The uptimeSec to set.
       * @return This builder for chaining.
       */
      public Builder setUptimeSec(long value) {
        copyOnWrite();
        instance.setUptimeSec(value);
        return this;
      }
      /**
       * <code>int64 uptime_sec = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUptimeSec() {
        copyOnWrite();
        instance.clearUptimeSec();
        return this;
      }

      /**
       * <code>int64 uptime_millis = 2;</code>
       * @return The uptimeMillis.
       */
      @java.lang.Override
      public long getUptimeMillis() {
        return instance.getUptimeMillis();
      }
      /**
       * <code>int64 uptime_millis = 2;</code>
       * @param value The uptimeMillis to set.
       * @return This builder for chaining.
       */
      public Builder setUptimeMillis(long value) {
        copyOnWrite();
        instance.setUptimeMillis(value);
        return this;
      }
      /**
       * <code>int64 uptime_millis = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUptimeMillis() {
        copyOnWrite();
        instance.clearUptimeMillis();
        return this;
      }

      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      @java.lang.Override
      public boolean hasError() {
        return instance.hasError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      @java.lang.Override
      public api.gravity.types.Types.ErrorInfo getError() {
        return instance.getError();
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder setError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.setError(value);
        return this;
        }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder setError(
          api.gravity.types.Types.ErrorInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setError(builderForValue.build());
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder mergeError(api.gravity.types.Types.ErrorInfo value) {
        copyOnWrite();
        instance.mergeError(value);
        return this;
      }
      /**
       * <code>.api.gravity.types.ErrorInfo error = 3;</code>
       */
      public Builder clearError() {  copyOnWrite();
        instance.clearError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.UptimeResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.TimeServiceOuterClass.UptimeResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "uptimeSec_",
              "uptimeMillis_",
              "error_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
                "\u0003\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.TimeServiceOuterClass.UptimeResponse> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.TimeServiceOuterClass.UptimeResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.TimeServiceOuterClass.UptimeResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.UptimeResponse)
    private static final api.gravity.v26.TimeServiceOuterClass.UptimeResponse DEFAULT_INSTANCE;
    static {
      UptimeResponse defaultInstance = new UptimeResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UptimeResponse.class, defaultInstance);
    }

    public static api.gravity.v26.TimeServiceOuterClass.UptimeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UptimeResponse> PARSER;

    public static com.google.protobuf.Parser<UptimeResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
