// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_service/v26/update_service.proto
// Protobuf Java Version: 4.26.1

package api.gravity.v26;

public final class UpdateServiceOuterClass {
  private UpdateServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface FileChunkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.gravity.v26.FileChunk)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string filename = 1;</code>
     * @return The filename.
     */
    java.lang.String getFilename();
    /**
     * <code>string filename = 1;</code>
     * @return The bytes for filename.
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <code>int32 chunk_number = 2;</code>
     * @return The chunkNumber.
     */
    int getChunkNumber();

    /**
     * <code>int32 total_chunks = 3;</code>
     * @return The totalChunks.
     */
    int getTotalChunks();

    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>bool is_last = 5;</code>
     * @return The isLast.
     */
    boolean getIsLast();

    /**
     * <code>string file_md5 = 6;</code>
     * @return The fileMd5.
     */
    java.lang.String getFileMd5();
    /**
     * <code>string file_md5 = 6;</code>
     * @return The bytes for fileMd5.
     */
    com.google.protobuf.ByteString
        getFileMd5Bytes();

    /**
     * <code>int64 file_size = 7;</code>
     * @return The fileSize.
     */
    long getFileSize();
  }
  /**
   * Protobuf type {@code api.gravity.v26.FileChunk}
   */
  public  static final class FileChunk extends
      com.google.protobuf.GeneratedMessageLite<
          FileChunk, FileChunk.Builder> implements
      // @@protoc_insertion_point(message_implements:api.gravity.v26.FileChunk)
      FileChunkOrBuilder {
    private FileChunk() {
      filename_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      fileMd5_ = "";
    }
    public static final int FILENAME_FIELD_NUMBER = 1;
    private java.lang.String filename_;
    /**
     * <code>string filename = 1;</code>
     * @return The filename.
     */
    @java.lang.Override
    public java.lang.String getFilename() {
      return filename_;
    }
    /**
     * <code>string filename = 1;</code>
     * @return The bytes for filename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(filename_);
    }
    /**
     * <code>string filename = 1;</code>
     * @param value The filename to set.
     */
    private void setFilename(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      filename_ = value;
    }
    /**
     * <code>string filename = 1;</code>
     */
    private void clearFilename() {

      filename_ = getDefaultInstance().getFilename();
    }
    /**
     * <code>string filename = 1;</code>
     * @param value The bytes for filename to set.
     */
    private void setFilenameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      filename_ = value.toStringUtf8();

    }

    public static final int CHUNK_NUMBER_FIELD_NUMBER = 2;
    private int chunkNumber_;
    /**
     * <code>int32 chunk_number = 2;</code>
     * @return The chunkNumber.
     */
    @java.lang.Override
    public int getChunkNumber() {
      return chunkNumber_;
    }
    /**
     * <code>int32 chunk_number = 2;</code>
     * @param value The chunkNumber to set.
     */
    private void setChunkNumber(int value) {
      
      chunkNumber_ = value;
    }
    /**
     * <code>int32 chunk_number = 2;</code>
     */
    private void clearChunkNumber() {

      chunkNumber_ = 0;
    }

    public static final int TOTAL_CHUNKS_FIELD_NUMBER = 3;
    private int totalChunks_;
    /**
     * <code>int32 total_chunks = 3;</code>
     * @return The totalChunks.
     */
    @java.lang.Override
    public int getTotalChunks() {
      return totalChunks_;
    }
    /**
     * <code>int32 total_chunks = 3;</code>
     * @param value The totalChunks to set.
     */
    private void setTotalChunks(int value) {
      
      totalChunks_ = value;
    }
    /**
     * <code>int32 total_chunks = 3;</code>
     */
    private void clearTotalChunks() {

      totalChunks_ = 0;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 4;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      data_ = value;
    }
    /**
     * <code>bytes data = 4;</code>
     */
    private void clearData() {

      data_ = getDefaultInstance().getData();
    }

    public static final int IS_LAST_FIELD_NUMBER = 5;
    private boolean isLast_;
    /**
     * <code>bool is_last = 5;</code>
     * @return The isLast.
     */
    @java.lang.Override
    public boolean getIsLast() {
      return isLast_;
    }
    /**
     * <code>bool is_last = 5;</code>
     * @param value The isLast to set.
     */
    private void setIsLast(boolean value) {
      
      isLast_ = value;
    }
    /**
     * <code>bool is_last = 5;</code>
     */
    private void clearIsLast() {

      isLast_ = false;
    }

    public static final int FILE_MD5_FIELD_NUMBER = 6;
    private java.lang.String fileMd5_;
    /**
     * <code>string file_md5 = 6;</code>
     * @return The fileMd5.
     */
    @java.lang.Override
    public java.lang.String getFileMd5() {
      return fileMd5_;
    }
    /**
     * <code>string file_md5 = 6;</code>
     * @return The bytes for fileMd5.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileMd5Bytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fileMd5_);
    }
    /**
     * <code>string file_md5 = 6;</code>
     * @param value The fileMd5 to set.
     */
    private void setFileMd5(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      fileMd5_ = value;
    }
    /**
     * <code>string file_md5 = 6;</code>
     */
    private void clearFileMd5() {

      fileMd5_ = getDefaultInstance().getFileMd5();
    }
    /**
     * <code>string file_md5 = 6;</code>
     * @param value The bytes for fileMd5 to set.
     */
    private void setFileMd5Bytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      fileMd5_ = value.toStringUtf8();

    }

    public static final int FILE_SIZE_FIELD_NUMBER = 7;
    private long fileSize_;
    /**
     * <code>int64 file_size = 7;</code>
     * @return The fileSize.
     */
    @java.lang.Override
    public long getFileSize() {
      return fileSize_;
    }
    /**
     * <code>int64 file_size = 7;</code>
     * @param value The fileSize to set.
     */
    private void setFileSize(long value) {
      
      fileSize_ = value;
    }
    /**
     * <code>int64 file_size = 7;</code>
     */
    private void clearFileSize() {

      fileSize_ = 0L;
    }

    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(api.gravity.v26.UpdateServiceOuterClass.FileChunk prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code api.gravity.v26.FileChunk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          api.gravity.v26.UpdateServiceOuterClass.FileChunk, Builder> implements
        // @@protoc_insertion_point(builder_implements:api.gravity.v26.FileChunk)
        api.gravity.v26.UpdateServiceOuterClass.FileChunkOrBuilder {
      // Construct using api.gravity.v26.UpdateServiceOuterClass.FileChunk.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string filename = 1;</code>
       * @return The filename.
       */
      @java.lang.Override
      public java.lang.String getFilename() {
        return instance.getFilename();
      }
      /**
       * <code>string filename = 1;</code>
       * @return The bytes for filename.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        return instance.getFilenameBytes();
      }
      /**
       * <code>string filename = 1;</code>
       * @param value The filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilename(
          java.lang.String value) {
        copyOnWrite();
        instance.setFilename(value);
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilename() {
        copyOnWrite();
        instance.clearFilename();
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       * @param value The bytes for filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFilenameBytes(value);
        return this;
      }

      /**
       * <code>int32 chunk_number = 2;</code>
       * @return The chunkNumber.
       */
      @java.lang.Override
      public int getChunkNumber() {
        return instance.getChunkNumber();
      }
      /**
       * <code>int32 chunk_number = 2;</code>
       * @param value The chunkNumber to set.
       * @return This builder for chaining.
       */
      public Builder setChunkNumber(int value) {
        copyOnWrite();
        instance.setChunkNumber(value);
        return this;
      }
      /**
       * <code>int32 chunk_number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunkNumber() {
        copyOnWrite();
        instance.clearChunkNumber();
        return this;
      }

      /**
       * <code>int32 total_chunks = 3;</code>
       * @return The totalChunks.
       */
      @java.lang.Override
      public int getTotalChunks() {
        return instance.getTotalChunks();
      }
      /**
       * <code>int32 total_chunks = 3;</code>
       * @param value The totalChunks to set.
       * @return This builder for chaining.
       */
      public Builder setTotalChunks(int value) {
        copyOnWrite();
        instance.setTotalChunks(value);
        return this;
      }
      /**
       * <code>int32 total_chunks = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalChunks() {
        copyOnWrite();
        instance.clearTotalChunks();
        return this;
      }

      /**
       * <code>bytes data = 4;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>bytes data = 4;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>bytes data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      /**
       * <code>bool is_last = 5;</code>
       * @return The isLast.
       */
      @java.lang.Override
      public boolean getIsLast() {
        return instance.getIsLast();
      }
      /**
       * <code>bool is_last = 5;</code>
       * @param value The isLast to set.
       * @return This builder for chaining.
       */
      public Builder setIsLast(boolean value) {
        copyOnWrite();
        instance.setIsLast(value);
        return this;
      }
      /**
       * <code>bool is_last = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsLast() {
        copyOnWrite();
        instance.clearIsLast();
        return this;
      }

      /**
       * <code>string file_md5 = 6;</code>
       * @return The fileMd5.
       */
      @java.lang.Override
      public java.lang.String getFileMd5() {
        return instance.getFileMd5();
      }
      /**
       * <code>string file_md5 = 6;</code>
       * @return The bytes for fileMd5.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFileMd5Bytes() {
        return instance.getFileMd5Bytes();
      }
      /**
       * <code>string file_md5 = 6;</code>
       * @param value The fileMd5 to set.
       * @return This builder for chaining.
       */
      public Builder setFileMd5(
          java.lang.String value) {
        copyOnWrite();
        instance.setFileMd5(value);
        return this;
      }
      /**
       * <code>string file_md5 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileMd5() {
        copyOnWrite();
        instance.clearFileMd5();
        return this;
      }
      /**
       * <code>string file_md5 = 6;</code>
       * @param value The bytes for fileMd5 to set.
       * @return This builder for chaining.
       */
      public Builder setFileMd5Bytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFileMd5Bytes(value);
        return this;
      }

      /**
       * <code>int64 file_size = 7;</code>
       * @return The fileSize.
       */
      @java.lang.Override
      public long getFileSize() {
        return instance.getFileSize();
      }
      /**
       * <code>int64 file_size = 7;</code>
       * @param value The fileSize to set.
       * @return This builder for chaining.
       */
      public Builder setFileSize(long value) {
        copyOnWrite();
        instance.setFileSize(value);
        return this;
      }
      /**
       * <code>int64 file_size = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileSize() {
        copyOnWrite();
        instance.clearFileSize();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:api.gravity.v26.FileChunk)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new api.gravity.v26.UpdateServiceOuterClass.FileChunk();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "filename_",
              "chunkNumber_",
              "totalChunks_",
              "data_",
              "isLast_",
              "fileMd5_",
              "fileSize_",
            };
            java.lang.String info =
                "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
                "\u0003\u0004\u0004\n\u0005\u0007\u0006\u0208\u0007\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<api.gravity.v26.UpdateServiceOuterClass.FileChunk> parser = PARSER;
          if (parser == null) {
            synchronized (api.gravity.v26.UpdateServiceOuterClass.FileChunk.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<api.gravity.v26.UpdateServiceOuterClass.FileChunk>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:api.gravity.v26.FileChunk)
    private static final api.gravity.v26.UpdateServiceOuterClass.FileChunk DEFAULT_INSTANCE;
    static {
      FileChunk defaultInstance = new FileChunk();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FileChunk.class, defaultInstance);
    }

    public static api.gravity.v26.UpdateServiceOuterClass.FileChunk getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FileChunk> PARSER;

    public static com.google.protobuf.Parser<FileChunk> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
